import os
import json
import unittest

class TestVersionContracts(unittest.TestCase):
    def setUp(self):
        self.project_root = os.path.dirname(os.path.dirname(__file__))
        self.version = "2.2.84"

    def test_manifest_version(self):
        manifest_path = os.path.join(self.project_root, "custom_components", "argus", "manifest.json")
        with open(manifest_path, "r") as f:
            manifest = json.load(f)
        self.assertEqual(manifest["version"], self.version, f"manifest.json version must be {self.version}")

    def test_const_version(self):
        const_path = os.path.join(self.project_root, "custom_components", "argus", "const.py")
        found = False
        with open(const_path, "r") as f:
            for line in f:
                if line.startswith("VERSION = "):
                    self.assertEqual(line.strip(), f'VERSION = "{self.version}"', f"const.py VERSION must be {self.version}")
                    found = True
                    break
        self.assertTrue(found, "VERSION not found in const.py")

    def test_release_notes_exist(self):
        notes_path = os.path.join(self.project_root, "docs", f"RELEASE_NOTES_{self.version}.md")
        self.assertTrue(os.path.exists(notes_path), f"Release notes must exist at docs/RELEASE_NOTES_{self.version}.md")

    def test_changelog_version(self):
        changelog_path = os.path.join(self.project_root, "CHANGELOG.md")
        with open(changelog_path, "r") as f:
            content = f.read()
        self.assertIn(f"## [{self.version}]", content, f"CHANGELOG.md must contain ## [{self.version}]")

    def test_frontend_bootstrap_version(self):
        # Optionally test the frontend loading scripts for the exact cache-bust version.
        # But this might be too brittle if it's generated by vite in the final form, though we can check argus-bootstrap.js
        # The Vite bundle stays cache-busted by the active integration version.
        bootstrap_path = os.path.join(self.project_root, "custom_components", "argus", "www", "argus-bootstrap.js")
        with open(bootstrap_path, "r") as f:
            content = f.read()
        self.assertIn(f"v={self.version}", content, f"argus-bootstrap.js must use v={self.version} for cache busting")

if __name__ == '__main__':
    unittest.main()
