import React,{useEffect,useMemo,useRef,useState,type ReactNode}from'react';
import {ErrorBoundary}from'./ErrorBoundary';
import{Responsive,WidthProvider,type Layout,type Layouts}from'react-grid-layout';
import type{ArgusBreakpoint,ArgusWidgetDefinition,ArgusWidgetSize,DashboardLayoutStorage}from'./types';
import{BREAKPOINTS,COLS,clampSizeForBreakpoint,defaultLayouts,firstFreePosition,getClosestWidgetSize,hasCollision,mergeLayouts,snapLayoutItemToSize}from'./layout';
import {useI18n}from'../../app/i18n';

const ResponsiveGridLayout=WidthProvider(Responsive);type EditorSetter=(value:boolean)=>void;
interface HostProps{widget:ArgusWidgetDefinition;content:ReactNode;editing:boolean;size:ArgusWidgetSize;bouncing:boolean;onSize:(size:ArgusWidgetSize)=>void;onHide:()=>void;onReset:()=>void}
function Host({widget,content,editing,size,bouncing,onSize,onHide,onReset}:HostProps){const{t}=useI18n();return <article className={`argus-widget argus-widget--size-${size.toLowerCase()}${bouncing?' argus-widget--settled':''}`}><header className="argus-widget__edit-header"><button type="button" className="argus-widget__drag-handle" aria-label={t('dashboard.move',{widget:widget.title})} title={t('dashboard.drag')}>⋮⋮</button><strong>{widget.title}</strong><details className="argus-widget__options"><summary aria-label={t('dashboard.options')} title={t('dashboard.options')}>•••</summary><div className="argus-widget__menu"><span>{t('dashboard.size')}</span><div>{(['XS','S','M','L','XL']as ArgusWidgetSize[]).map(value=><button type="button" className={value===size?'active':''} onClick={()=>onSize(value)} key={value}>{value}</button>)}</div><button type="button" onClick={onReset}>{t('dashboard.resetWidget')}</button><button type="button" onClick={onHide}>{t('dashboard.hide')}</button></div></details></header><div className={`argus-widget__content${widget.kind==='access-control'?' argus-widget__content--access':''}`}>{content}</div></article>}
export function ArgusDashboard({widgets,storage,userId,dashboardId,onEditing,registerEditor,renderWidget}:{widgets:ArgusWidgetDefinition[];storage:DashboardLayoutStorage;userId:string;dashboardId:string;onEditing:(v:boolean)=>void;registerEditor:(setter:EditorSetter)=>void;renderWidget:(widget:ArgusWidgetDefinition)=>ReactNode}){
 const{t}=useI18n();
 const defaults=useMemo(()=>Object.fromEntries(widgets.map(w=>[w.id,w.visible])),[widgets]);
 const[layouts,setLayouts]=useState<Layouts>(defaultLayouts),[visibility,setVisibility]=useState<Record<string,boolean>>(defaults),[editing,setEditing]=useState(false),[hydrated,setHydrated]=useState(false),[bp,setBp]=useState<ArgusBreakpoint>('lg'),[message,setMessage]=useState(''),[settled,setSettled]=useState('');
 const lastValid=useRef<Layouts>(defaultLayouts),timer=useRef<number>(),settleTimer=useRef<number>(),wasEditing=useRef(false);
 useEffect(()=>{registerEditor(setEditing)},[registerEditor]);
 useEffect(()=>{let active=true;setHydrated(false);Promise.all([storage.load(userId,dashboardId),storage.loadVisibility?.(userId,dashboardId)]).then(([value,storedVisibility])=>{if(!active)return;const merged=mergeLayouts(value);setLayouts(merged);lastValid.current=merged;if(storedVisibility)setVisibility({...defaults,...storedVisibility});setHydrated(true)});return()=>{active=false}},[storage,userId,dashboardId,defaults]);
 useEffect(()=>{onEditing(editing);if(hydrated&&wasEditing.current&&!editing)storage.save(userId,dashboardId,lastValid.current);wasEditing.current=editing},[editing,hydrated,onEditing,storage,userId,dashboardId]);
 useEffect(()=>{const key=(event:KeyboardEvent)=>{if(!editing)return;if(event.key==='Escape'){setEditing(false);setMessage(t('dashboard.finished'))}else if(event.key==='Enter'&&event.target===document.body)setEditing(false)};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[editing,t]);
 useEffect(()=>()=>{clearTimeout(timer.current);clearTimeout(settleTimer.current)},[]);
 const save=(next:Layouts,now=false)=>{setLayouts(next);lastValid.current=next;clearTimeout(timer.current);timer.current=window.setTimeout(()=>storage.save(userId,dashboardId,next),now?0:550)};
 const finishResize=(id:string)=>{setSettled(id);clearTimeout(settleTimer.current);settleTimer.current=window.setTimeout(()=>setSettled(''),260)};
 const setVisible=(id:string,value:boolean)=>{const next={...visibility,[id]:value};setVisibility(next);storage.saveVisibility?.(userId,dashboardId,next);setMessage(value?t('dashboard.visible'):t('dashboard.invisible'))};
 const replaceItem=(id:string,nextItem:Layout,label:string)=>{const base=lastValid.current,current=base[bp]||[],others=current.filter(x=>x.i!==id),safe=hasCollision(others,nextItem)?firstFreePosition(others,nextItem,COLS[bp]):nextItem;const next={...base,[bp]:current.map(x=>x.i===id?safe:x)};save(next,true);setMessage(label)};
 const chooseSize=(id:string,size:ArgusWidgetSize)=>{const current=(lastValid.current[bp]||[]).find(x=>x.i===id);if(!current)return;const d=clampSizeForBreakpoint(size,COLS[bp]);replaceItem(id,{...current,...d,x:Math.max(0,Math.min(current.x,COLS[bp]-d.w))},t('dashboard.resized',{size}));finishResize(id)};
 const resetWidget=(id:string)=>{const base=(defaultLayouts[bp]||[]).find(x=>x.i===id);if(base)replaceItem(id,{...base},t('dashboard.widgetRestored'))};
 const resize=(_layout:Layout[],_old:Layout,value:Layout)=>{const snapped=snapLayoutItemToSize(value,COLS[bp]);const size=getClosestWidgetSize(snapped.w,snapped.h,COLS[bp]);replaceItem(value.i,snapped,t('dashboard.resized',{size}));finishResize(value.i)};
 const reset=async()=>{if(!confirm(t('dashboard.confirm')))return;await storage.reset(userId,dashboardId);const clean=mergeLayouts(null);setVisibility(defaults);save(clean,true);setMessage(t('dashboard.restored'))};
 const currentLayout=layouts[bp]||[];
 if(!hydrated)return <section className="argus-dashboard"><div className="argus-dashboard__feedback" aria-live="polite">{t('dashboard.loading')}</div></section>;
 return <section className={`argus-dashboard ${editing?'argus-dashboard--editing':''}`}><div className="argus-dashboard__feedback" aria-live="polite">{message}</div><ErrorBoundary><ResponsiveGridLayout className="argus-dashboard-grid" layouts={layouts} breakpoints={BREAKPOINTS} cols={COLS} rowHeight={84} margin={[12,12]} containerPadding={[12,12]} compactType={null} preventCollision allowOverlap={false} isBounded isDraggable={editing} isResizable={editing} draggableHandle=".argus-widget__drag-handle" resizeHandles={['se']} onBreakpointChange={value=>setBp(value as ArgusBreakpoint)} onLayoutChange={(_,all)=>{if(editing){setLayouts(all);lastValid.current=all}}} onResizeStop={resize} onDragStop={(_,__,value)=>{const others=(lastValid.current[bp]||[]).filter(x=>x.i!==value.i);if(hasCollision(others,value)){setLayouts({...lastValid.current});setMessage(t('dashboard.blocked'));return}replaceItem(value.i,value,t('dashboard.saved'))}} useCSSTransforms>{widgets.filter(w=>visibility[w.id]!==false).map(w=>{const item=currentLayout.find(x=>x.i===w.id);const size=item?getClosestWidgetSize(item.w,item.h,COLS[bp]):w.size;return <div key={w.id}><ErrorBoundary><Host widget={w} content={renderWidget(w)} editing={editing} size={size} bouncing={settled===w.id} onSize={value=>chooseSize(w.id,value)} onHide={()=>setVisible(w.id,false)} onReset={()=>resetWidget(w.id)}/></ErrorBoundary></div>})}</ResponsiveGridLayout></ErrorBoundary><nav className="argus-dashboard__toolbar" aria-label={t('dashboard.toolbar')}><button type="button" onClick={()=>setEditing(v=>!v)}>{editing?((window as any)._argusDashboardReadyBtn||t('dashboard.done')):((window as any)._argusDashboardEditBtn||t('dashboard.edit'))}</button>{editing&&<><button type="button" onClick={reset}>{(window as any)._argusDashboardResetBtn||t('dashboard.reset')}</button><div className="argus-dashboard__visibility" aria-label={t('dashboard.hidden')}>{widgets.filter(w=>visibility[w.id]===false).map(w=><button type="button" key={w.id} onClick={()=>setVisible(w.id,true)}>{t('dashboard.show',{widget:w.title})}</button>)}</div></>}</nav></section>
}
export default ArgusDashboard;
