import type {ArgusBreakpoint, ArgusWidgetSize, DashboardLayoutStorage, Layout, Layouts, StoredDashboardLayout} from './types';

export const BREAKPOINTS={lg:1200,md:996,sm:768,xs:480,xxs:0} as const;
export const COLS={lg:12,md:8,sm:4,xs:2,xxs:2} as const;
export const ARGUS_WIDGET_SIZES:Record<ArgusWidgetSize,{w:number;h:number}>={XS:{w:2,h:2},S:{w:3,h:3},M:{w:3,h:4},L:{w:6,h:4},XL:{w:6,h:8}};
const item=(i:string,x:number,y:number,w:number,h:number):Layout=>({i,x,y,w,h,minW:1,minH:1,maxW:12,maxH:12});
export const defaultLayouts:Layouts={
 lg:[item('activity-history',0,0,3,4),item('automations',3,0,3,4),item('backup-restore',6,0,3,4),item('support-argus',9,0,2,2),item('security-status',9,2,3,3),item('access-control',0,5,6,3),item('alarm-configuration',6,5,6,8)],
 md:[item('activity-history',0,0,4,4),item('automations',4,0,4,4),item('backup-restore',0,4,4,4),item('support-argus',4,4,2,2),item('access-control',4,6,4,3),item('alarm-configuration',0,9,8,8),item('security-status',0,17,4,3)],
 sm:[item('activity-history',0,0,4,4),item('automations',0,4,4,4),item('backup-restore',0,8,4,4),item('support-argus',0,12,2,2),item('access-control',0,14,4,3),item('alarm-configuration',0,17,4,8),item('security-status',0,25,4,3)],
 xs:[item('activity-history',0,0,2,4),item('automations',0,4,2,4),item('backup-restore',0,8,2,4),item('support-argus',0,12,2,2),item('access-control',0,14,2,3),item('alarm-configuration',0,17,2,8),item('security-status',0,25,2,3)],
 xxs:[item('activity-history',0,0,2,4),item('automations',0,4,2,4),item('backup-restore',0,8,2,4),item('support-argus',0,12,2,2),item('access-control',0,14,2,3),item('alarm-configuration',0,17,2,8),item('security-status',0,25,2,3)],
};
export function getClosestWidgetSize(w:number,h:number,cols:number):ArgusWidgetSize{return Object.entries(ARGUS_WIDGET_SIZES).map(([size,d])=>({size:size as ArgusWidgetSize,distance:Math.abs(Math.min(d.w,cols)-w)+Math.abs(d.h-h)})).sort((a,b)=>a.distance-b.distance)[0]?.size??'S'}
export function clampSizeForBreakpoint(size:ArgusWidgetSize,cols:number){const d=ARGUS_WIDGET_SIZES[size];return{w:Math.min(d.w,cols),h:d.h}}
export function snapLayoutItemToSize(value:Layout,cols:number){const size=getClosestWidgetSize(value.w,value.h,cols),d=clampSizeForBreakpoint(size,cols);return{...value,w:d.w,h:d.h,x:Math.max(0,Math.min(value.x,cols-d.w)),size}}
export function hasCollision(layout:Layout[],candidate:Layout){return layout.some(x=>x.i!==candidate.i&&candidate.x<x.x+x.w&&candidate.x+candidate.w>x.x&&candidate.y<x.y+x.h&&candidate.y+candidate.h>x.y)}
export function firstFreePosition(layout:Layout[],candidate:Layout,cols:number):Layout{for(let y=0;y<240;y++)for(let x=0;x<=cols-candidate.w;x++){const next={...candidate,x,y};if(!hasCollision(layout,next))return next}return{...candidate,x:0,y:Math.max(0,...layout.map(x=>x.y+x.h))}}
export function mergeLayouts(saved:Layouts|null):Layouts{const result:Layouts={};(Object.keys(COLS)as ArgusBreakpoint[]).forEach(bp=>{const cols=COLS[bp],source=Array.isArray(saved?.[bp])?saved![bp]:[],map=new Map(source.map(x=>[x.i,x]));const known=(defaultLayouts[bp]||[]).map(base=>{const old=map.get(base.i);if(!old)return{...base};const w=Math.min(Math.max(1,old.w),cols);return{...base,...old,w,x:Math.max(0,Math.min(old.x,cols-w)),y:Math.max(0,old.y)}});const knownIds=new Set(known.map(x=>x.i)),extra=source.filter(x=>!knownIds.has(x.i)).map(x=>({...x,w:Math.min(Math.max(1,x.w),cols),x:Math.max(0,Math.min(x.x,cols-Math.min(x.w,cols))),y:Math.max(0,x.y)}));result[bp]=[...known,...extra]});return result}
export class LocalStorageDashboardLayoutStorage implements DashboardLayoutStorage{private key(u:string,d:string){return`argus:dashboard-layout:${u}:${d}`}private read(u:string,d:string):StoredDashboardLayout|null{try{const value=JSON.parse(localStorage.getItem(this.key(u,d))||'null')as StoredDashboardLayout|null;return value?.layoutVersion!=null&&value.layoutVersion>=1?value:null}catch{return null}}private write(u:string,d:string,value:StoredDashboardLayout){localStorage.setItem(this.key(u,d),JSON.stringify(value))}async load(u:string,d:string){const value=this.read(u,d);return value?mergeLayouts(value.layouts):null}async save(u:string,d:string,layouts:Layouts){const old=this.read(u,d);this.write(u,d,{layoutVersion:1,layouts,visibility:old?.visibility,updatedAt:new Date().toISOString()})}async loadVisibility(u:string,d:string){return this.read(u,d)?.visibility??null}async saveVisibility(u:string,d:string,visibility:Record<string,boolean>){const old=this.read(u,d);this.write(u,d,{layoutVersion:1,layouts:old?.layouts??mergeLayouts(null),visibility,updatedAt:new Date().toISOString()})}async reset(u:string,d:string){localStorage.removeItem(this.key(u,d))}}
