declare module '*argus-ui-audit-fixes.js'{export function applyUiAuditFixes(C:CustomElementConstructor|undefined):void}
declare module '*premium-experience.js'{export function applyPremiumExperience(C:CustomElementConstructor|undefined):void}
declare module '*argus-grid-polish.js'{export function applyGridPolish(C:CustomElementConstructor|undefined):void}
declare module '*argus-fullscreen-polish.js'{export function applyFullscreenPolish(C:CustomElementConstructor|undefined):void}
declare module '*argus-v2013-audit-fixes.js'{export function applyV2012AuditFixes(C:CustomElementConstructor|undefined):void}
declare module '*argus-performance-profile.js'{export function applyPerformanceProfile(C:CustomElementConstructor|undefined):void}
declare module '*argus-visual-container-fixes.js'{export function applyVisualContainerFixes(C:CustomElementConstructor|undefined):void}
declare module '*argus-complete-content-fixes.js'{export function applyCompleteContentFixes(C:CustomElementConstructor|undefined):void}
declare module '*argus-runtime-visual-fixes.js'{export function applyRuntimeVisualFixes(C:CustomElementConstructor|undefined):void}
declare module '*argus-bg-sensor-availability-fixes.js'{export function applyBgSensorAvailabilityFixes(C:CustomElementConstructor|undefined):void}
declare module '*argus-battery-ui-fixes.js'{export function applyBatteryUiFixes(C:CustomElementConstructor|undefined):void}
declare module '*argus-deep-repair.js'{export function applyDeepRepair(C:CustomElementConstructor|undefined):void}
declare module '*argus-light-capability-fixes.js'{export function applyLightCapabilityFixes(C:CustomElementConstructor|undefined):void}
declare module '*argus-personalization-toggle-fix.js'{export function applyPersonalizationToggleFix(C:CustomElementConstructor|undefined):void}
declare module '*argus-dashboard-scroll-fixes.js'{export function applyDashboardScrollFixes(C:CustomElementConstructor|undefined):void}
declare module '*argus-v2041-audit-repair.js'{export function applyV2041AuditRepair(C:CustomElementConstructor|undefined):void}
declare module '*argus-v2042-stability.js'{export function applyV2042Stability(C:CustomElementConstructor|undefined):void}
declare module '*argus-v2043-visual-fix.js'{export function applyV2043VisualFix(C:CustomElementConstructor|undefined):void}
declare module '*argus-v2045-trigger-sensors.js'{export function applyV2045TriggerSensors(C:CustomElementConstructor|undefined):void}
declare module '*argus-v2046-active-visuals.js'{export function applyV2046ActiveVisuals(C:CustomElementConstructor|undefined):void}
declare module '*argus-v2049-responsive-widgets.js'{export function applyV2049ResponsiveWidgets(C:CustomElementConstructor|undefined):void}
declare module '*argus-motion-system.js'{export function applyMotionSystem(C:CustomElementConstructor|undefined):void}
declare module '*argus-v2050-stable-render.js'{export function applyStableInstancesRender(C:CustomElementConstructor|undefined):void}
declare module '*argus-v2050-alarm-visuals.js'{export function applyV2050AlarmVisuals(C:CustomElementConstructor|undefined):void}
declare module '*argus-v2050-widget-layouts.js'{export function applyV2050WidgetLayouts(C:CustomElementConstructor|undefined):void}
