// @ts-nocheck
const DEFAULT_LAYOUT=[{id:'activity',size:'M',hidden:false},{id:'modes',size:'M',hidden:false},{id:'automations',size:'M',hidden:false},{id:'access',size:'M',hidden:false},{id:'backup',size:'S',hidden:false},{id:'github',size:'S',hidden:false}];
const VALID_SIZES=new Set(['S','M','L','XL']);
const CLOCK_COPY={es:['Formato de hora','Automático (Home Assistant)','12 horas (AM/PM)','24 horas'],en:['Time format','Automatic (Home Assistant)','12-hour (AM/PM)','24-hour'],fr:["Format de l'heure",'Automatique (Home Assistant)','12 heures (AM/PM)','24 heures'],pt:['Formato de hora','Automático (Home Assistant)','12 horas (AM/PM)','24 horas'],it:['Formato ora','Automatico (Home Assistant)','12 ore (AM/PM)','24 ore'],zh:['时间格式','自动（Home Assistant）','12 小时（AM/PM）','24 小时'],ru:['Формат времени','Автоматически (Home Assistant)','12 часов (AM/PM)','24 часа']};
const VALID_CLOCK_FORMATS=new Set(['auto','12h','24h']);
const lang=p=>String(p._manualLang||p._hass?.language||p._hass?.locale?.language||'en').toLowerCase().split(/[-_]/)[0];
const clone=v=>JSON.parse(JSON.stringify(v));
function normalizeLayout(value){if(!Array.isArray(value))return null;const seen=new Set(),result=[];value.forEach(item=>{const id=String(item?.id||'');if(!id||seen.has(id))return;seen.add(id);result.push({id,size:VALID_SIZES.has(item?.size)?item.size:'M',hidden:Boolean(item?.hidden)})});DEFAULT_LAYOUT.forEach(item=>{if(!seen.has(item.id))result.push({...item})});return result.length?result:null}
function localLayout(){try{return normalizeLayout(JSON.parse(localStorage.getItem('argus-widgets-v2')||localStorage.getItem('argus-widgets-v1')||'null'))}catch(_){return null}}
function persistLocal(layout){try{const text=JSON.stringify(layout);localStorage.setItem('argus-widgets-v2',text);localStorage.setItem('argus-widgets-v1',text)}catch(_){}}
function ensureClockControl(panel){const root=panel.shadowRoot,grid=root?.querySelector('.personalize-grid');if(!grid)return;let field=root.getElementById('argus-clock-format-field');if(!field){field=document.createElement('div');field.id='argus-clock-format-field';field.className='personalize-field pf-clock';field.innerHTML='<label class="setting-label" id="argus-clock-format-label" for="argus-clock-format-select"></label><select id="argus-clock-format-select" class="glass-control"><option value="auto"></option><option value="12h"></option><option value="24h"></option></select>';grid.appendChild(field);field.querySelector('select')?.addEventListener('change',event=>{panel._clockFormat=event.target.value;panel._ui=panel._ui||{};panel._ui.clock_format=event.target.value;panel._lastClockUpdate=0;panel._updateHeroContext?.();panel._renderEntries?.()})}const copy=CLOCK_COPY[lang(panel)]||CLOCK_COPY.en,label=field.querySelector('label'),options=field.querySelectorAll('option');if(label)label.textContent='🕐 '+copy[0];options.forEach((option,index)=>{option.textContent=copy[index+1]});const select=field.querySelector('select');if(select){const storedFmt=VALID_CLOCK_FORMATS.has(panel._clockFormat)?panel._clockFormat:(VALID_CLOCK_FORMATS.has(panel._ui?.clock_format)?panel._ui.clock_format:'auto');if(select.value!==storedFmt)select.value=storedFmt}}
function installStyles(panel){if(panel.shadowRoot?.getElementById('argus-v2012-audit-style'))return;const style=document.createElement('style');style.id='argus-v2012-audit-style';style.textContent=`
:host{--argus-clear-bg:linear-gradient(105deg,rgba(30,62,78,.34),rgba(9,25,37,.50));--argus-clear-border:rgba(255,255,255,.18)}
.entry,.entry-bg,.entry-bg>*:first-child,.entry .wx,.entry .wx-atmosphere,.entry-content{border-radius:32px!important}.entry{isolation:isolate;overflow:hidden!important;transition:border-radius .28s ease,box-shadow .28s ease,transform .28s ease,opacity .2s ease!important}.entry::after{border-radius:32px!important}
.entry-content.security-console{display:grid!important;grid-template-columns:minmax(220px,1fr) minmax(160px,220px) minmax(260px,1fr)!important;grid-template-rows:auto minmax(0,1fr)!important;grid-template-areas:'hud hud hud' 'modes icon sensors'!important;align-items:center!important;gap:18px 24px!important;padding:24px!important}.security-console .console-hud{grid-area:hud!important}.security-console .liquid-stack{grid-area:modes!important;width:100%!important;max-width:none!important}.security-console .entry-icon{grid-area:icon!important;width:100%!important;justify-self:center!important}.security-console .console-sensors{grid-area:sensors!important;width:100%!important;max-width:none!important}
.security-console .liquid-btn,.security-console .console-keypad,.console-hud-loc,.console-hud-time,.console-hud-temp,.console-hud-tpill,.argus-connection-pill{background:var(--argus-clear-bg)!important;border:1px solid var(--argus-clear-border)!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.18),0 7px 18px rgba(0,0,0,.12)!important}.security-console .liquid-btn.active{background:linear-gradient(105deg,color-mix(in srgb,var(--btn-bg,#34c759) 58%,transparent),rgba(8,25,36,.44))!important}.security-console .liquid-btn{transition:transform .28s cubic-bezier(.2,.8,.2,1),background .35s ease,border-color .35s ease,box-shadow .35s ease,color .25s ease!important}.security-console .liquid-btn:hover{transform:translateY(-2px)!important}.security-console .liquid-btn:active{transform:scale(.975)!important}
.entry-icon{position:relative!important;contain:layout paint;transform:translateZ(0)}.entry-icon>svg{position:relative;z-index:2;transform-origin:center;transition:filter .5s ease,opacity .35s ease!important}.entry-icon.argus-shield-changing>svg{animation:argusShieldIn .52s cubic-bezier(.2,.82,.2,1) both!important}.argus-old-shield{position:absolute;inset:0;z-index:3;display:grid;place-items:center;pointer-events:none;animation:argusShieldOut .5s cubic-bezier(.4,0,.2,1) both}.argus-old-shield svg{width:100%;height:auto;max-width:inherit}@keyframes argusShieldIn{0%{opacity:.15;transform:scale(.94);filter:blur(4px)}55%{opacity:1;transform:scale(1.025);filter:blur(0)}100%{opacity:1;transform:scale(1)}}@keyframes argusShieldOut{0%{opacity:1;transform:scale(1);filter:blur(0)}100%{opacity:0;transform:scale(1.045);filter:blur(5px)}}
.console-hud{grid-template-columns:minmax(0,1fr) minmax(150px,220px) minmax(0,1fr)!important}.console-hud-loc{grid-column:1!important;justify-self:start!important;min-width:0!important;max-width:100%!important}.argus-connection-pill{grid-column:2!important;justify-self:center!important}.console-hud-right{grid-column:3!important;justify-self:end!important;min-width:0!important;max-width:100%!important}
.hero-context{display:grid!important;grid-template-columns:auto minmax(0,1fr)!important;align-items:center!important;gap:12px!important;min-width:0!important}.hero-clock{display:grid!important;grid-template-rows:auto auto!important;align-content:center!important;justify-items:end!important;min-width:76px!important;padding-right:12px!important}.hero-clock strong,.hero-clock span{width:100%!important;text-align:right!important;white-space:nowrap!important;font-variant-numeric:tabular-nums!important}.hero-clock span{overflow:hidden!important;text-overflow:ellipsis!important;max-width:14ch!important}.hero-pills{min-width:0!important;flex-wrap:wrap!important}
.pf-clock{grid-area:clock}.personalize-grid{grid-template-areas:'home temp' 'panel weather' 'hub clock' 'emergency emergency'!important}.ios-fullscreen .entry-content.security-console{grid-template-columns:minmax(230px,340px) minmax(280px,1fr) minmax(250px,340px)!important;grid-template-areas:'hud hud hud' 'modes icon sensors'!important;align-items:center!important;overflow:hidden!important}.ios-fullscreen .entry-icon{justify-self:center!important;align-self:center!important}.ios-fullscreen .entry-icon svg{will-change:transform,opacity,filter}:host(.argus-exiting-fullscreen) .entry{pointer-events:none!important;transition:none!important}
@media(max-width:900px){.entry-content.security-console,.ios-fullscreen .entry-content.security-console{grid-template-columns:minmax(0,1fr)!important;grid-template-rows:auto auto auto auto!important;grid-template-areas:'hud' 'icon' 'modes' 'sensors'!important;justify-items:center!important;padding:68px 16px 24px!important;gap:16px!important;overflow-y:auto!important;align-content:start!important}.console-hud{width:100%!important;grid-template-columns:minmax(0,1fr) auto!important;grid-template-areas:'location connection' 'readings readings'!important;gap:8px!important}.console-hud-loc{grid-area:location!important}.argus-connection-pill{grid-area:connection!important}.console-hud-right{grid-area:readings!important;justify-self:stretch!important;justify-content:flex-start!important;overflow-x:auto!important}.security-console .entry-icon{display:flex!important;min-height:150px!important;max-width:280px!important}.security-console .entry-icon svg{width:min(58vw,260px)!important;max-width:260px!important;min-width:0!important}.security-console .liquid-stack,.security-console .console-sensors{width:100%!important;max-width:440px!important;margin:0 auto!important}.security-console .console-sensors{max-height:none!important;overflow:visible!important}.hero-context{width:100%!important;grid-template-columns:auto minmax(0,1fr)!important}.hero-clock{justify-items:start!important;padding:0 12px 0 0!important}.hero-clock strong,.hero-clock span{text-align:left!important}.hero-pills{justify-content:flex-start!important}.personalize-grid{grid-template-columns:1fr!important;grid-template-areas:'home' 'temp' 'weather' 'clock' 'panel' 'hub' 'emergency'!important}}
@media(max-width:520px){.entry,.entry-bg,.entry-bg>*:first-child,.entry .wx,.entry-content{border-radius:26px!important}.entry-content.security-console,.ios-fullscreen .entry-content.security-console{padding:72px 12px 20px!important}.security-console .liquid-stack{grid-template-columns:repeat(2,minmax(0,1fr))!important}.security-console .liquid-btn{min-width:0!important;white-space:normal!important}.console-hud-loc{font-size:10px!important}.console-hud-right{scrollbar-width:none}.hero-context{grid-template-columns:1fr!important}.hero-clock{border:0!important;padding:0!important;justify-items:start!important}.hero-pills{width:100%!important}.ios-fullscreen{overflow:hidden!important}.ios-fullscreen .entry-content.security-console{height:100dvh!important;max-height:100dvh!important}.ios-fullscreen .console-sensors{padding-bottom:28px!important}}
@media(prefers-reduced-motion:reduce){.argus-old-shield{display:none!important}.entry-icon.argus-shield-changing>svg{animation:none!important}}
`;panel.shadowRoot.appendChild(style)}
function snapshotShields(panel){return [...(panel.shadowRoot?.querySelectorAll('.entry')||[])].map(entry=>entry.querySelector('.entry-icon>svg')?.outerHTML||null)}
function animateShieldChanges(panel,before){panel.shadowRoot?.querySelectorAll('.entry').forEach((entry,index)=>{const icon=entry.querySelector('.entry-icon'),svg=icon?.querySelector(':scope>svg'),previous=before[index];if(!icon||!svg||!previous||previous===svg.outerHTML)return;icon.querySelector('.argus-old-shield')?.remove();const old=document.createElement('div');old.className='argus-old-shield';old.innerHTML=previous;icon.prepend(old);icon.classList.remove('argus-shield-changing');void icon.offsetWidth;icon.classList.add('argus-shield-changing');setTimeout(()=>{old.remove();icon.classList.remove('argus-shield-changing')},560)})}
function captureLayout(panel){const grid=panel.shadowRoot?.getElementById('widget-grid');if(!grid)return normalizeLayout(panel._widgetConfig)||clone(DEFAULT_LAYOUT);const current=new Map((panel._widgetConfig||[]).map(item=>[item.id,item]));const result=[...grid.children].filter(el=>el.classList.contains('panel')&&!el.classList.contains('dashboard-instances')).map(el=>{const id=el.id.replace(/^w-/,''),prior=current.get(id)||{};return{id,size:VALID_SIZES.has(el.dataset.size)?el.dataset.size:(VALID_SIZES.has(prior.size)?prior.size:'M'),hidden:el.classList.contains('widget-hidden-preview')||el.style.display==='none'||Boolean(prior.hidden)}});return normalizeLayout(result)||clone(DEFAULT_LAYOUT)}
function saveLayout(panel,layout){panel._widgetConfig=clone(layout);persistLocal(layout);panel._ui=panel._ui||{};const dashboard={...(panel._ui.dashboard||{}),widget_layout:clone(layout)};panel._ui.dashboard=dashboard;const payload={dashboard};if(panel._dashboard?.entry_id)payload.entry_id=panel._dashboard.entry_id;panel._widgetSaveChain=(panel._widgetSaveChain||Promise.resolve()).catch(()=>{}).then(()=>panel._send('argus/save_ui',payload)).then(response=>{if(response?.ui?.dashboard)panel._ui.dashboard=response.ui.dashboard;panel.dataset.widgetSave='saved'}).catch(error=>{panel.dataset.widgetSave='local';console.error('Argus widget layout saved locally; server save failed',error)})}
export function applyV2012AuditFixes(ArgusPanel){if(!ArgusPanel||ArgusPanel.__v2012AuditFixes)return;ArgusPanel.__v2012AuditFixes=true;const proto=ArgusPanel.prototype,connected=proto.connectedCallback,disconnected=proto.disconnectedCallback,load=proto._load,render=proto._renderEntries,init=proto._initWidgetGrid,save=proto._saveWidgetLayout,persist=proto._persistPersonalization,translations=proto._applyTranslations,exit=proto._exitFullscreenView;
proto.connectedCallback=function(){installStyles(this);const result=connected?.call(this);this._argusExitCapture=event=>{if(this._argusExiting)event.stopImmediatePropagation()};document.addEventListener('fullscreenchange',this._argusExitCapture,true);document.addEventListener('webkitfullscreenchange',this._argusExitCapture,true);return result};
proto.disconnectedCallback=function(){document.removeEventListener('fullscreenchange',this._argusExitCapture,true);document.removeEventListener('webkitfullscreenchange',this._argusExitCapture,true);return disconnected?.call(this)};
proto._load=async function(){const result=await load?.call(this);if(this._ui){this._clockFormat=VALID_CLOCK_FORMATS.has(this._ui.clock_format)?this._ui.clock_format:'auto';ensureClockControl(this)}return result};
proto._applyTranslations=function(){const result=translations?.call(this);ensureClockControl(this);return result};
proto._renderEntries=function(){const before=snapshotShields(this),result=render?.call(this);installStyles(this);requestAnimationFrame(()=>animateShieldChanges(this,before));return result};
proto._initWidgetGrid=function(){const server=normalizeLayout(this._ui?.dashboard?.widget_layout),local=localLayout();this._widgetConfig=clone(server||local||DEFAULT_LAYOUT);persistLocal(this._widgetConfig);this._widgetConfigLoaded=true;const result=init?.call(this);this._renderWidgetLayout?.();return result};
proto._saveWidgetLayout=function(){save?.call(this);saveLayout(this,captureLayout(this))};
proto._persistPersonalization=async function(){this._clockFormat=VALID_CLOCK_FORMATS.has(this.shadowRoot?.getElementById('argus-clock-format-select')?.value)?this.shadowRoot.getElementById('argus-clock-format-select').value:(VALID_CLOCK_FORMATS.has(this._clockFormat)?this._clockFormat:'auto');const result=await persist?.call(this);this._ui=this._ui||{};this._ui.clock_format=this._clockFormat;const payload={clock_format:this._clockFormat};if(this._ui.weather_source)payload.weather_source=this._ui.weather_source;if(this._ui.temperature_source)payload.temperature_source=this._ui.temperature_source;if(this._dashboard?.entry_id)payload.entry_id=this._dashboard.entry_id;const response=await this._send('argus/save_ui',payload);if(response?.ui)this._ui={...this._ui,...response.ui};ensureClockControl(this);this._lastClockUpdate=0;this._updateHeroContext?.();this._renderEntries?.();return result};
proto._exitFullscreenView=async function(){this._argusExiting=true;this.classList.add('argus-exiting-fullscreen');try{return await exit?.call(this)}finally{requestAnimationFrame(()=>requestAnimationFrame(()=>{this._argusExiting=false;this.classList.remove('argus-exiting-fullscreen')}))}};
}
