// @ts-nocheck
const D=[{id:'activity',size:'M',hidden:false},{id:'modes',size:'M',hidden:false},{id:'automations',size:'M',hidden:false},{id:'access',size:'M',hidden:false},{id:'backup',size:'S',hidden:false},{id:'github',size:'S',hidden:false}];
const panels=g=>[...(g?.children||[])].filter(x=>x.classList.contains('panel')&&!x.classList.contains('dashboard-instances'));
const sync=(e,on)=>{if(!e)return;const a=e.querySelector('[data-fullscreen]');let b=e.querySelector('[data-exit-fullscreen]');if(!b){b=document.createElement('button');b.className='ghost entry-exit-fs';b.dataset.exitFullscreen='';b.textContent='×';b.style.cssText='position:absolute;top:16px;left:16px;z-index:100;padding:9px 13px;font-size:18px;background:rgba(0,0,0,.55);border-radius:14px;color:white;border:1px solid rgba(255,255,255,.25)';b.onclick=()=>e.getRootNode().host._exitFullscreenView();e.appendChild(b)}if(a)a.style.display=on?'none':'block';b.style.display=on?'block':'none'};
function css(p){if(p.shadowRoot?.getElementById('argus-ui-fix'))return;const s=document.createElement('style');s.id='argus-ui-fix';s.textContent=`.grid.editing .panel.widget-hidden-preview{opacity:.48!important}.widget-drag-handle{min-height:44px;display:flex;align-items:center;justify-content:center}.ios-fullscreen .entry-content.security-console{display:grid!important;grid-template-columns:minmax(230px,340px) minmax(150px,1fr) minmax(230px,380px)!important;grid-template-rows:auto minmax(0,1fr)!important;grid-template-areas:'hud hud hud' 'modes icon sensors'!important;gap:20px 32px!important;padding:56px 48px 32px!important;overflow:hidden!important}.ios-fullscreen .console-hud{grid-area:hud!important}.ios-fullscreen .liquid-stack{grid-area:modes!important;width:100%!important}.ios-fullscreen .entry-icon{grid-area:icon!important}.ios-fullscreen .console-sensors{grid-area:sensors!important;max-height:60vh!important;overflow:auto!important}@media(max-width:900px){.ios-fullscreen .entry-content.security-console{grid-template-columns:1fr!important;grid-template-rows:auto auto auto auto!important;grid-template-areas:'hud' 'icon' 'modes' 'sensors'!important;padding:64px 18px 22px!important;overflow-y:auto!important}.ios-fullscreen .liquid-stack,.ios-fullscreen .console-sensors{max-width:420px!important;margin:auto!important}}`;p.shadowRoot.appendChild(s)}
function localize(p){const r=p.shadowRoot;if(!r)return;const t=(k,f)=>p._t?.(k)||f;const e=r.getElementById('edit-widgets-label');if(e)e.textContent=p._widgetEditing?'✓ '+(p._t?.('done')||'Done'):'⚙️ '+t('edit_dashboard','Configurar widgets');r.querySelectorAll('.widget-drag-handle').forEach(x=>x.textContent='⋮⋮ '+t('drag','Arrastrar'));r.querySelectorAll('.widget-toggle-btn').forEach(x=>x.textContent=/mostrar|show|afficher|mostra|显示|показ|show/i.test(x.textContent)?t('show','Mostrar'):t('hide','Ocultar'));r.querySelectorAll('.console-empty').forEach(x=>x.textContent=/omit|bypass|ignor|exclu|绕过|исключ/i.test(x.textContent)?t('all_sensors_bypassed','Todos los sensores están omitidos'):t('no_sensors_configured','Sin sensores configurados'));r.querySelectorAll('.entry').forEach(x=>[...x.children].filter(y=>['CONECTADO','CONNECTED'].includes(y.textContent?.trim())).forEach(y=>{const d=y.firstElementChild;y.textContent='';if(d)y.appendChild(d);y.append(t('connected','Conectado'))}))}
export function applyUiAuditFixes(C){if(!C||C.__uiAudit)return;C.__uiAudit=true;const p=C.prototype,conn=p.connectedCallback,trans=p._applyTranslations,render=p._renderEntries,init=p._initWidgetGrid,save=p._saveWidgetLayout;
p.connectedCallback=function(){css(this);return conn?.call(this)};
p._applyTranslations=function(){const x=trans?.call(this);localize(this);return x};
p._renderEntries=function(){const x=render?.call(this);css(this);this.shadowRoot?.querySelectorAll('.entry').forEach((e,i)=>sync(e,this._fullscreenIdx===i||e.classList.contains('ios-fullscreen')));localize(this);return x};
p._toggleFullscreen=function(e){e=e||this.shadowRoot?.querySelector('.entry');if(!e)return;this._fullscreenIdx=Number(e.querySelector('[data-fullscreen]')?.dataset.fullscreen||0);this._kioskLocked=false;this._kioskTarget=e;this.classList.add('fullscreen-active');e.classList.add('ios-fullscreen');sync(e,true);document.body.style.overflow='hidden';const f=e.requestFullscreen||e.webkitRequestFullscreen;f?.call(e).catch?.(()=>{})};
p._exitFullscreenView=async function(){try{if(document.fullscreenElement)await document.exitFullscreen();else document.webkitExitFullscreen?.()}catch(_){}this.shadowRoot?.querySelectorAll('.entry.ios-fullscreen').forEach(e=>{e.classList.remove('ios-fullscreen');sync(e,false)});this.classList.remove('fullscreen-active');this._fullscreenIdx=-1;this._kioskLocked=false;this._kioskTarget=null;document.body.style.overflow=''};
p._initWidgetGrid=function(){if(!this._widgetConfigLoaded){const server=this._ui?.dashboard?.widget_layout;if(server)try{localStorage.setItem('argus-widgets-v1',JSON.stringify(server))}catch(_){}this._widgetConfigLoaded=true}init?.call(this);const g=this.shadowRoot?.getElementById('widget-grid');panels(g).forEach(e=>e.draggable=!!this._widgetEditing);if(g&&!g._auditDrag){g._auditDrag=true;g.addEventListener('dragover',ev=>{if(!this._widgetEditing)return;ev.preventDefault();const d=g.querySelector('.dragging');if(!d)return;let n=null,z=Infinity;panels(g).filter(x=>x!==d).forEach(x=>{const r=x.getBoundingClientRect(),q=Math.hypot(ev.clientX-r.x-r.width/2,ev.clientY-r.y-r.height/2);if(q<z){z=q;n=x}});if(n){const r=n.getBoundingClientRect();n[ev.clientX>r.x+r.width/2||ev.clientY>r.y+r.height/2?'after':'before'](d)}})}localize(this)};
p._saveWidgetLayout=function(){save?.call(this);const layout=this._widgetConfig||D;this._ui=this._ui||{};const dashboard={...(this._ui.dashboard||{}),widget_layout:layout};this._ui.dashboard=dashboard;clearTimeout(this._widgetSaveTimer);this._widgetSaveTimer=setTimeout(()=>this._send('argus/save_ui',{dashboard}).catch(e=>console.error('Widget layout save failed',e)),180)};
p._changeWidgetSize=function(id,size){const c=(this._widgetConfig||[]).find(x=>x.id===id);if(!c)return;c.size=size;const e=this.shadowRoot?.getElementById('w-'+id);if(e)e.dataset.size=size;this._renderWidgetLayout();this._saveWidgetLayout()};
p._toggleWidgetVisibility=function(id){const c=(this._widgetConfig||[]).find(x=>x.id===id);if(!c)return;c.hidden=!c.hidden;const e=this.shadowRoot?.getElementById('w-'+id);if(e){e.classList.toggle('widget-hidden-preview',c.hidden&&this._widgetEditing);e.style.display=c.hidden&&!this._widgetEditing?'none':''}this._renderWidgetLayout();this._saveWidgetLayout()};}
