// @ts-nocheck
const STATUS_TEXT={es:{on:'Conectado',off:'Argus desconectado · HA sin conexión'},en:{on:'Connected',off:'Argus disconnected · HA offline'},fr:{on:'Connecté',off:'Argus déconnecté · HA hors ligne'},pt:{on:'Conectado',off:'Argus desconectado · HA sem conexão'},it:{on:'Connesso',off:'Argus disconnesso · HA offline'},zh:{on:'已连接',off:'Argus 已断开 · HA 离线'},ru:{on:'Подключено',off:'Argus отключён · HA не в сети'}};
const languageFor=panel=>{const raw=String(panel._manualLang||panel._hass?.language||panel._hass?.locale?.language||'en').toLowerCase().split(/[-_]/)[0];return STATUS_TEXT[raw]||STATUS_TEXT.en};
function installStyles(panel){if(panel.shadowRoot?.getElementById('argus-fullscreen-polish-style'))return;const style=document.createElement('style');style.id='argus-fullscreen-polish-style';style.textContent=`
.console-hud{display:grid!important;grid-template-columns:minmax(0,1fr) auto minmax(0,1fr)!important;align-items:center!important;gap:12px!important;padding:0!important;background:transparent!important;border:0!important;border-radius:0!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;overflow:visible!important}
.console-hud-loc{justify-self:start!important;max-width:100%!important;padding:9px 14px!important;border-radius:999px!important;background:linear-gradient(135deg,rgba(255,255,255,.18),rgba(255,255,255,.07))!important;border:1px solid rgba(255,255,255,.24)!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.28),0 8px 22px rgba(0,0,0,.16)!important;backdrop-filter:blur(20px) saturate(145%)!important;-webkit-backdrop-filter:blur(20px) saturate(145%)!important}
.console-hud-right{justify-self:end!important;display:flex!important;align-items:center!important;justify-content:flex-end!important;gap:7px!important;min-width:0!important;background:transparent!important;border:0!important;box-shadow:none!important}
.console-hud-time,.console-hud-temp,.console-hud-tpill{display:inline-flex!important;align-items:center!important;min-height:30px!important;box-sizing:border-box!important;padding:6px 10px!important;border-radius:999px!important;background:linear-gradient(135deg,rgba(255,255,255,.18),rgba(255,255,255,.07))!important;border:1px solid rgba(255,255,255,.24)!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.28),0 8px 22px rgba(0,0,0,.14)!important;backdrop-filter:blur(20px) saturate(145%)!important;-webkit-backdrop-filter:blur(20px) saturate(145%)!important}
.console-hud-temps{display:flex!important;gap:7px!important;flex-wrap:nowrap!important}
.argus-connection-pill{position:static!important;inset:auto!important;transform:none!important;grid-column:2!important;justify-self:center!important;z-index:30!important;display:inline-flex!important;align-items:center!important;justify-content:center!important;gap:7px!important;min-height:30px!important;width:auto!important;max-width:max-content!important;box-sizing:border-box!important;padding:6px 12px!important;border-radius:999px!important;white-space:nowrap!important;font-size:11px!important;font-weight:800!important;letter-spacing:.02em!important;backdrop-filter:blur(20px) saturate(150%)!important;-webkit-backdrop-filter:blur(20px) saturate(150%)!important;transition:color .25s ease,background .25s ease,border-color .25s ease,box-shadow .25s ease!important}
.argus-connection-pill[data-online="true"]{color:#7ff8bd!important;background:linear-gradient(135deg,rgba(36,188,129,.28),rgba(36,188,129,.10))!important;border:1px solid rgba(78,231,163,.48)!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.24),0 0 20px rgba(36,188,129,.20)!important}
.argus-connection-pill[data-online="false"]{color:#ffd09a!important;background:linear-gradient(135deg,rgba(255,145,43,.32),rgba(130,66,8,.18))!important;border:1px solid rgba(255,171,76,.62)!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.22),0 0 22px rgba(255,132,28,.28)!important}
.argus-connection-dot{width:7px!important;height:7px!important;flex:0 0 7px!important;border-radius:50%!important;background:currentColor!important;box-shadow:0 0 9px currentColor!important}
.console-sensors{position:relative!important;isolation:isolate!important;display:grid!important;grid-auto-rows:minmax(48px,auto)!important;align-content:start!important;gap:10px!important;padding:8px 7px!important;max-height:min(64vh,560px)!important;overflow-y:auto!important;overflow-x:hidden!important;overscroll-behavior:contain!important;scrollbar-gutter:stable!important;background:transparent!important;border:0!important;box-shadow:none!important;filter:none!important;transform:none!important;contain:layout paint!important}
.console-sensors::before,.console-sensors::after{display:none!important;content:none!important}
.console-sensor{position:relative!important;z-index:1!important;min-width:0!important;margin:0!important;overflow:hidden!important;isolation:isolate!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.20),inset 0 0 0 1px rgba(255,255,255,.04)!important;transform:translateZ(0)!important}
.console-sensor.open{box-shadow:inset 0 1px 0 rgba(255,255,255,.18),inset 0 0 0 1px rgba(255,102,92,.16)!important}
.console-sensors::-webkit-scrollbar{width:6px}.console-sensors::-webkit-scrollbar-track{background:transparent}.console-sensors::-webkit-scrollbar-thumb{background:rgba(255,255,255,.25);border-radius:999px}
@media(min-width:901px){.ios-fullscreen .entry-content.security-console{grid-template-columns:minmax(210px,260px) minmax(280px,1fr) minmax(250px,340px)!important;gap:18px 20px!important;padding:48px 32px 28px!important}.ios-fullscreen .entry-content.security-console .entry-icon{min-width:280px!important;min-height:300px!important;overflow:visible!important}.ios-fullscreen .entry-content.security-console .entry-icon svg{width:clamp(280px,34vw,500px)!important;max-width:500px!important;min-width:280px!important;filter:drop-shadow(0 0 46px rgba(94,255,167,.30))!important}.ios-fullscreen .entry-content.security-console .console-sensors{width:100%!important;max-width:340px!important}}
@media(max-width:900px){.console-hud{grid-template-columns:minmax(0,1fr) auto!important;grid-template-areas:'location connection' 'readings readings'!important}.console-hud-loc{grid-area:location!important}.argus-connection-pill{grid-area:connection!important}.console-hud-right{grid-area:readings!important;justify-self:stretch!important;justify-content:flex-start!important;overflow-x:auto!important}.ios-fullscreen .entry-content.security-console .entry-icon{display:flex!important;min-height:190px!important}.ios-fullscreen .entry-content.security-console .entry-icon svg{display:block!important;width:clamp(180px,46vw,300px)!important;max-width:300px!important}.console-sensors{width:100%!important;max-width:460px!important;max-height:42vh!important}}
`;panel.shadowRoot?.appendChild(style)}
function connectionPill(entry){let pill=entry.querySelector('.argus-connection-pill');if(pill)return pill;pill=[...entry.children].find(el=>el.tagName==='DIV'&&(el.getAttribute('style')||'').includes('left:50%')&&(el.getAttribute('style')||'').includes('top:12px'));if(!pill)return null;pill.className='argus-connection-pill';pill.removeAttribute('style');const hud=entry.querySelector('.console-hud'),right=hud?.querySelector('.console-hud-right');if(hud)hud.insertBefore(pill,right||null);return pill}
function isConnected(panel){const haReady=Boolean(panel._hass)&&panel._hass?.connection?.connected!==false;return navigator.onLine!==false&&haReady}
function refreshConnection(panel){const copy=languageFor(panel),online=isConnected(panel);panel.shadowRoot?.querySelectorAll('.entry').forEach(entry=>{const pill=connectionPill(entry);if(!pill)return;pill.dataset.online=String(online);pill.setAttribute('role','status');pill.setAttribute('aria-live','polite');pill.replaceChildren();const dot=document.createElement('i');dot.className='argus-connection-dot';const label=document.createElement('span');label.className='argus-connection-label';label.textContent=online?copy.on:copy.off;pill.append(dot,label)})}
function polish(panel){installStyles(panel);refreshConnection(panel)}
export function applyFullscreenPolish(ArgusPanel){if(!ArgusPanel||ArgusPanel.__fullscreenPolish)return;ArgusPanel.__fullscreenPolish=true;const proto=ArgusPanel.prototype,connected=proto.connectedCallback,disconnected=proto.disconnectedCallback,render=proto._renderEntries,hassDescriptor=Object.getOwnPropertyDescriptor(proto,'hass');
proto.connectedCallback=function(){const result=connected?.call(this);this._argusOnlineHandler=()=>refreshConnection(this);window.addEventListener('online',this._argusOnlineHandler);window.addEventListener('offline',this._argusOnlineHandler);clearInterval(this._argusConnectivityTimer);this._argusConnectivityTimer=setInterval(()=>refreshConnection(this),2500);queueMicrotask(()=>polish(this));return result};
proto.disconnectedCallback=function(){window.removeEventListener('online',this._argusOnlineHandler);window.removeEventListener('offline',this._argusOnlineHandler);clearInterval(this._argusConnectivityTimer);return disconnected?.call(this)};
proto._renderEntries=function(){const result=render?.call(this);polish(this);return result};
if(hassDescriptor?.set)Object.defineProperty(proto,'hass',{configurable:true,enumerable:hassDescriptor.enumerable,get:hassDescriptor.get,set(value){hassDescriptor.set.call(this,value);queueMicrotask(()=>refreshConnection(this))}});
}
