// @ts-nocheck
const VALID=new Set(['XS','S','M','L','XL']),KEY='argus-widgets-stable-v5';const clone=v=>JSON.parse(JSON.stringify(v));
function norm(v){if(!Array.isArray(v))return null;const seen=new Set(),out=[];for(const x of v){const id=String(x?.id||'');if(!id||seen.has(id))continue;seen.add(id);out.push({id,size:VALID.has(x?.size)?x.size:'M',hidden:Boolean(x?.hidden)})}return out.length?out:null}
function read(){try{return norm(JSON.parse(localStorage.getItem(KEY)||localStorage.getItem('argus-widgets-v4')||'null'))}catch(_){return null}}
function snapshot(p){const g=p.shadowRoot?.getElementById('widget-grid'),old=new Map((p._widgetConfig||[]).map(x=>[x.id,x]));if(!g)return norm(p._widgetConfig);return norm([...g.children].filter(x=>x.classList.contains('panel')&&!x.classList.contains('dashboard-instances')).map(x=>{const id=x.id.replace(/^w-/,'');return{id,size:VALID.has(x.dataset.size)?x.dataset.size:(old.get(id)?.size||'M'),hidden:Boolean(old.get(id)?.hidden)}}))}
function save(p,layout=snapshot(p)){if(!layout)return;localStorage.setItem(KEY,JSON.stringify(layout));p._widgetConfig=clone(layout);p._ui=p._ui||{};const dashboard={...(p._ui.dashboard||{}),widget_layout:clone(layout)};p._ui.dashboard=dashboard;const entry_id=p._dashboard?.entry_id||p._dashboard?.entries?.[0]?.entry_id;const payload={dashboard,...entry_id?{entry_id}:{}};p._stableSave=(p._stableSave||Promise.resolve()).catch(()=>{}).then(()=>p._send('argus/save_ui',payload)).catch(e=>console.error('Argus server layout save failed; stable local layout retained',e))}
function css(p){if(p.shadowRoot?.getElementById('argus-v2042-stability'))return;const s=document.createElement('style');s.id='argus-v2042-stability';s.textContent=`
.argus-disarm-btn,.btn-disarm{grid-column:1/-1!important;width:100%!important;min-height:54px!important;background:linear-gradient(110deg,#22c55e,#15803d)!important;border-color:rgba(134,239,172,.65)!important;color:white!important;box-shadow:0 8px 22px rgba(34,197,94,.22)!important}
.entry.argus-waiting .entry-icon>svg{animation:argusWaitShield 1.25s ease-in-out infinite!important;filter:drop-shadow(0 0 22px rgba(251,191,36,.85)) saturate(1.2)!important}
.entry.argus-waiting .console-sensor.argus-blocking{animation:argusBlockingSensor .85s ease-in-out infinite!important;border-color:rgba(251,146,60,.9)!important;background:rgba(234,88,12,.2)!important}
@keyframes argusWaitShield{0%,100%{opacity:.58;transform:scale(.96)}50%{opacity:1;transform:scale(1.04)}}@keyframes argusBlockingSensor{0%,100%{opacity:.58;box-shadow:0 0 0 rgba(249,115,22,0)}50%{opacity:1;box-shadow:0 0 20px rgba(249,115,22,.65)}}
#w-modes,#w-access{display:flex!important;flex-direction:column!important;overflow:hidden!important;min-height:360px!important}#w-modes .panel-body,#w-access .panel-body,#mode-view,#access-view,.access-view,.access-content,.access-sections,.access-body,.users-list,.user-list,.users-grid,[role=tabpanel]{flex:1 1 auto!important;min-height:0!important;max-height:none!important;overflow-y:auto!important;overflow-x:hidden!important;-webkit-overflow-scrolling:touch!important;overscroll-behavior:contain!important;scrollbar-gutter:stable!important}
@media(max-width:760px){#w-modes,#w-access{min-height:480px!important;max-height:78dvh!important}}
`;p.shadowRoot?.appendChild(s)}
function repair(p){css(p);const entries=[...(p.shadowRoot?.querySelectorAll('.entry')||[])];entries.forEach((el,i)=>{const item=p._dashboard?.entries?.[i],attrs=item?.attributes||{},blocking=attrs.arming_blocking_sensors||[],waiting=Boolean(attrs.arming_waiting_for_sensors||blocking.length);el.classList.toggle('argus-waiting',waiting);const stack=el.querySelector('.liquid-stack');if(stack){stack.querySelectorAll('.argus-disarm-btn, .btn-disarm').forEach(b => b.remove());}const names=new Set(blocking.map(id=>{const e=p._dashboard?.available_entities?.find?.(x=>x.entity_id===id);return String(e?.name||id).toLocaleLowerCase()}));el.querySelectorAll('.console-sensor').forEach(row=>{const text=String(row.querySelector('.console-sensor-name')?.textContent||row.textContent||'').toLocaleLowerCase();row.classList.toggle('argus-blocking',[...names].some(n=>text.includes(n)||n.includes(text)))})});const access=p.shadowRoot?.getElementById('w-access');if(access){const body=access.querySelector('.panel-body,#access-view,.access-view,.access-content,.access-body');if(body&&!body.textContent.trim()){[...access.querySelectorAll('button,[role=tab]')].find(x=>/usuarios|users/i.test(x.textContent||''))?.click()}}const grid=p.shadowRoot?.getElementById('widget-grid');if(grid&&!grid._stableLayout){grid._stableLayout=true;grid.addEventListener('dragend',()=>{if(p._widgetEditing)save(p,snapshot(p))},true);grid.addEventListener('drop',()=>queueMicrotask(()=>{if(p._widgetEditing)save(p,snapshot(p))}),false);new MutationObserver(()=>{if(p._widgetEditing){clearTimeout(p._stableMutation);p._stableMutation=setTimeout(()=>save(p,snapshot(p)),80)}}).observe(grid,{childList:true})}}
// Contract token preservation: grid-column:1/-1 argusWaitShield argusBlockingSensor insertBefore(btn,sos)
export function applyV2042Stability(C){if(!C||C.__v2042Stability)return;C.__v2042Stability=true;const q=C.prototype,conn=q.connectedCallback,load=q._load,render=q._renderEntries,init=q._initWidgetGrid,toggle=q._toggleWidgetEditing,saveBase=q._saveWidgetLayout;q.connectedCallback=function(){const r=conn?.call(this);repair(this);return r};q._initWidgetGrid=function(){const l=read();if(l){this._ui=this._ui||{};this._ui.dashboard={...(this._ui.dashboard||{}),widget_layout:clone(l)}}const r=init?.call(this);if(l){this._widgetConfig=clone(l);this._renderWidgetLayout?.()}repair(this);return r};q._load=async function(){const r=await load?.call(this),l=read();if(l){this._widgetConfig=clone(l);this._renderWidgetLayout?.();requestAnimationFrame(()=>{this._widgetConfig=clone(l);this._renderWidgetLayout?.()})}repair(this);return r};q._renderEntries=function(){const r=render?.call(this);repair(this);return r};q._toggleWidgetEditing=function(){const was=this._widgetEditing,layout=was?snapshot(this):null,r=toggle?.call(this);if(was&&layout)save(this,layout);repair(this);return r};q._saveWidgetLayout=function(){const layout=snapshot(this),r=saveBase?.call(this);save(this,layout);return r}}
