// @ts-nocheck
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const clamp=(v,a=0,b=1)=>Math.min(b,Math.max(a,num(v)));

function installStyles(panel){
 if(panel.shadowRoot?.getElementById('argus-v2066-style'))return;
 const s=document.createElement('style');s.id='argus-v2066-style';s.textContent=`
:host{--v2066-glass:linear-gradient(135deg,color-mix(in srgb,var(--card-background-color,#101827) 34%,transparent),color-mix(in srgb,var(--card-background-color,#101827) 15%,transparent));--v2066-border:color-mix(in srgb,var(--primary-text-color,#fff) 22%,transparent);--v2066-text:var(--primary-text-color,#f7f9ff);--v2066-muted:var(--secondary-text-color,rgba(247,249,255,.72))}
:host *:not(.wx-webgl),:host *::before,:host *::after{animation:none!important;transition:none!important}
.glass,.liquid-glass,.panel,.entry,.mode-section-card,.user-card,.file-card,.log-item,.personalize-section,.sos-configuration{background:var(--v2066-glass)!important;border:1px solid var(--v2066-border)!important;box-shadow:inset 0 1px 0 color-mix(in srgb,var(--primary-text-color,#fff) 16%,transparent),0 14px 38px rgba(0,0,0,.16)!important;backdrop-filter:blur(24px) saturate(145%)!important;-webkit-backdrop-filter:blur(24px) saturate(145%)!important;color:var(--v2066-text)!important}
.panel h1,.panel h2,.panel h3,.panel h4,.panel-title,.section-title,.setting-label,.mode-section-title,.widget-title,.settings-section-title,.access-section-title{color:var(--v2066-text)!important;opacity:1!important;text-shadow:none!important}.panel p,.panel small,.hint,.muted,.setting-help,.mode-sensor-none{color:var(--v2066-muted)!important;opacity:1!important}
button,input,select,textarea,.glass-control{color:var(--v2066-text)!important;-webkit-text-fill-color:var(--v2066-text)!important;background-color:color-mix(in srgb,var(--card-background-color,#101827) 38%,transparent)!important;border-color:var(--v2066-border)!important}button{min-height:44px;touch-action:manipulation}button:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible{outline:3px solid color-mix(in srgb,var(--primary-color,#2783de) 76%,white)!important;outline-offset:2px!important}
.wx-atmosphere{position:absolute;inset:0;overflow:hidden;isolation:isolate;background:linear-gradient(180deg,#4e9bd1,#b7d9e8)!important}.wx-atmosphere.night{background:linear-gradient(180deg,#030817,#102544)!important}.wx-webgl{position:absolute;inset:0;width:100%;height:100%;display:block;pointer-events:none;opacity:1!important}
.wx-celestial,.wx-cloudfield,.wx-precip,.wx-starfield,.wx-lightning,.wx-fog-real,.wx-seasonal,.wx-horizon{display:none!important}
@media(prefers-color-scheme:light){:host{--v2066-glass:linear-gradient(135deg,rgba(255,255,255,.56),rgba(255,255,255,.24));--v2066-border:rgba(255,255,255,.72);--v2066-text:var(--primary-text-color,#172033);--v2066-muted:var(--secondary-text-color,#4c586d)}}`;
 panel.shadowRoot?.appendChild(s);
}

function openPanicSelector(panel){
 panel._selectorTarget='panic';panel._selected=Array.isArray(panel._panicOutputs)?[...panel._panicOutputs]:[];
 if(typeof panel._openSelector==='function'){panel._openSelector('panic');return true;}
 if(typeof panel._openEntitySelector==='function'){panel._openEntitySelector('panic');return true;}
 return false;
}
function bindSos(panel){
 const root=panel.shadowRoot;if(!root||root.__argusV2066SosBound)return;root.__argusV2066SosBound=true;
 root.addEventListener('click',event=>{const button=event.target?.closest?.('button');if(!button)return;const label=`${button.textContent||''} ${button.getAttribute('aria-label')||''} ${button.title||''}`.toLowerCase();const selector=button.matches('[data-select-sos-output],[data-action="select-panic-outputs"],#select-sos-outputs,#btn-select-sos-outputs')||(/seleccionar|select|añadir|add/.test(label)&&/luces|lights|sirenas|sirens|scripts|acciones sos|sos actions/.test(label));if(selector)queueMicrotask(()=>{if(!root.querySelector('.modal.open,.ios-confirm-backdrop.open,[role="dialog"][open]'))openPanicSelector(panel)});if(button.matches('[data-remove-sos-output]'))queueMicrotask(async()=>{const outputs=[...new Set(panel._panicOutputs||[])],settings={...(panel._panicOutputSettings||{})};Object.keys(settings).forEach(id=>{if(!outputs.includes(id))delete settings[id]});const entry_id=panel._dashboard?.entry_id||panel._dashboard?.entries?.[0]?.entry_id;try{await panel._send?.('argus/save_panic_output_profile',{...(entry_id?{entry_id}:{}),outputs,settings})}catch(error){console.error('Argus v2.0.66 SOS remove failed',error)}})},true);
}

export function applyV2066Webgl2AndUi(C){
 if(!C||C.__argusV2066Webgl2AndUi)return;C.__argusV2066Webgl2AndUi=true;const p=C.prototype,connected=p.connectedCallback,render=p._renderEntries;
 p.connectedCallback=function(){installStyles(this);const value=connected?.call(this);bindSos(this);return value};
 p._renderEntries=function(){const value=render?.call(this);installStyles(this);bindSos(this);return value};
 p._renderAtmosphere=function(ws,isNight){const a=ws?.attributes||{},condition=[ws?.state,ws?.condition,a.condition,a.forecast?.[0]?.condition].filter(Boolean).join(' ').toLowerCase(),has=re=>re.test(condition),storm=has(/lightning|thunder|storm|tormenta/),drizzle=has(/drizzle|llovizna/),rain=storm||drizzle||has(/rain|pouring|shower|lluvia/),snow=has(/snow|snowy|sleet|hail|nieve|granizo/),fog=has(/fog|mist|haze|niebla|bruma/),clouds=storm||rain||snow||fog||has(/cloud|overcast|partly|nublado|nuboso/),wind=clamp(num(a.wind_speed??a.windSpeed??a.wind_gust_speed)/55+(has(/wind|breezy|ventoso/)?0.35:0),0,1.25),temp=num(this._lastTemp??a.temperature??20);return `<div class="wx wx-atmosphere ${isNight?'night':'day'}"><canvas class="wx-webgl" aria-hidden="true" data-rain="${rain?1:0}" data-drizzle="${drizzle?1:0}" data-snow="${snow?1:0}" data-fog="${fog?1:0}" data-storm="${storm?1:0}" data-clouds="${clouds?1:0}" data-wind="${wind.toFixed(3)}" data-temp="${temp}" data-night="${isNight?1:0}"></canvas></div>`};
 p._initWeatherWebGL=function(canvas){
  canvas?._argusWebglStop?.();const gl=canvas?.getContext?.('webgl2',{alpha:false,antialias:false,depth:false,stencil:false,powerPreference:'low-power',preserveDrawingBuffer:false});if(!gl){canvas?.classList?.add('webgl-unavailable');return}
  const vertex=`#version 300 es
in vec2 p;out vec2 uv;void main(){uv=p*.5+.5;gl_Position=vec4(p,0.0,1.0);}`;
  const fragment=`#version 300 es
precision highp float;in vec2 uv;out vec4 FragColor;uniform float time,rain,snow,fog,storm,clouds,wind,temp,night;
float h(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453123);}float n(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);return mix(mix(h(i),h(i+vec2(1,0)),f.x),mix(h(i+vec2(0,1)),h(i+vec2(1)),f.x),f.y);}float fbm(vec2 p){float v=0.0,a=.5;for(int i=0;i<4;i++){v+=a*n(p);p=p*2.03+17.17;a*=.5;}return v;}
float cm(vec2 p){return smoothstep(.48,.76,fbm(p)*.82+fbm(p*2.7+8.4)*.32);}vec4 cloud(vec2 q,float t){vec2 p=vec2(q.x*2.35,q.y*1.45)+vec2(t*(.018+.055*wind),-.08);float tr=1.0,li=0.0,de=0.0;for(int i=0;i<4;i++){float fi=float(i),d=cm(p+vec2(fi*.055,fi*.025));de+=d*.25;li+=d*tr*(.43+fi*.07);tr*=1.0-d*.22;}float a=clamp(de*1.75*smoothstep(.18,.42,q.y)*(1.0-smoothstep(.88,1.02,q.y))*clouds,0.0,.88);vec3 dc=mix(vec3(.48,.56,.64),vec3(1.0,.98,.94),clamp(li,0.0,1.0)),nc=mix(vec3(.055,.08,.14),vec3(.28,.37,.52),clamp(li,0.0,1.0));return vec4(mix(dc,nc,night)*a,a);}
float stars(vec2 q,float t){vec2 g=q*vec2(190,105),id=floor(g),f=fract(g)-.5;float s=h(id);return step(.985,s)*(1.0-smoothstep(.015,.075,length(f)))*(.58+.42*sin(t*(1.5+s*2.0)+s*90.0));}float rl(vec2 q,float t,float l){q.x+=wind*q.y*.23;vec2 g=q*vec2(24.0+l*9.0,8.0+l*4.0),id=floor(g),f=fract(g);f.y=fract(f.y+t*(2.1+l*.8)+h(id));float x=abs(f.x-(.5-f.y*(.12+wind*.16)));return(1.0-smoothstep(.006,.035,x))*(1.0-smoothstep(.12,.96,f.y));}float sl(vec2 q,float t,float l){vec2 g=q*vec2(15.0+l*6.0,10.0+l*4.0),id=floor(g),f=fract(g)-.5;f.y=fract(f.y+t*(.13+l*.055)+h(id))-.5;f.x+=sin(t*.8+h(id)*6.283)*.18+wind*.12*sin(t);return 1.0-smoothstep(.035,.09+l*.012,length(f));}
vec3 sky(vec2 q){return mix(mix(vec3(.66,.82,.91),vec3(.08,.38,.70),q.y),mix(vec3(.055,.12,.23),vec3(.006,.012,.045),q.y),night);}void main(){float t=time*.001;vec2 q=uv;vec3 col=sky(q);vec2 bp=mix(vec2(.77,.73),vec2(.72,.74),night);float d=length((q-bp)*vec2(1,1.55)),disk=1.0-smoothstep(.055,.068,d),glow=exp(-d*10.5);col+=mix(vec3(1,.74,.28),vec3(.82,.9,1),night)*(disk+glow*.34);if(night>.01)col+=vec3(.72,.83,1)*stars(q,t)*night*(1.0-clouds*.78);if(night>.5&&temp<9.0&&storm<.5){float band=pow(max(0.0,1.0-abs(q.y-(.63+sin(q.x*5.0+t*.12)*.08))/.28),3.0),au=fbm(vec2(q.x*3.2+t*.035,q.y*5.0));col+=mix(vec3(.02,.8,.48),vec3(.38,.12,.9),au)*band*au*.38*(1.0-fog*.65);}vec4 c=cloud(q,t);col=col*(1.0-c.a)+c.rgb;if(rain>0.0){float r=rl(q,t,0.0)+rl(q,t,1.0)*.62+rl(q,t,2.0)*.34;col+=vec3(.58,.76,.94)*r*rain*.78;col*=1.0-rain*.12;}if(snow>0.0){float s=sl(q,t,0.0)+sl(q,t,1.0)*.65+sl(q,t,2.0)*.35;col+=vec3(1)*s*snow*.88;}if(fog>0.0){float f=smoothstep(.28,.82,fbm(vec2(q.x*3.0+t*.035,q.y*5.0-t*.012)))*fog*.66;col=mix(col,mix(vec3(.72,.79,.83),vec3(.15,.2,.29),night),f);}if(storm>0.0){float pulse=pow(max(0.0,sin(t*.73+n(vec2(floor(t*.37),4.0))*6.283)),42.0),bolt=(1.0-smoothstep(.006,.025,abs(q.x-(.62+sin(q.y*19.0)*.035))))*smoothstep(.22,.78,q.y)*pulse;col+=vec3(.83,.9,1)*(pulse*.68+bolt*1.8)*storm;}col=col/(vec3(1)+col*.18);FragColor=vec4(col,1);}`;
  const compile=(type,source)=>{const sh=gl.createShader(type);gl.shaderSource(sh,source);gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS)){console.error('Argus WebGL2 shader',gl.getShaderInfoLog(sh));gl.deleteShader(sh);return null}return sh},vs=compile(gl.VERTEX_SHADER,vertex),fs=compile(gl.FRAGMENT_SHADER,fragment);if(!vs||!fs)return;const program=gl.createProgram();gl.attachShader(program,vs);gl.attachShader(program,fs);gl.linkProgram(program);gl.deleteShader(vs);gl.deleteShader(fs);if(!gl.getProgramParameter(program,gl.LINK_STATUS)){console.error('Argus WebGL2 link',gl.getProgramInfoLog(program));return}const vao=gl.createVertexArray(),buffer=gl.createBuffer();gl.bindVertexArray(vao);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,1,1]),gl.STATIC_DRAW);const pos=gl.getAttribLocation(program,'p');gl.enableVertexAttribArray(pos);gl.vertexAttribPointer(pos,2,gl.FLOAT,false,0,0);const names=['time','rain','snow','fog','storm','clouds','wind','temp','night'],loc=Object.fromEntries(names.map(x=>[x,gl.getUniformLocation(program,x)])),values={rain:Math.max(num(canvas.dataset.rain),num(canvas.dataset.drizzle)*.45),snow:num(canvas.dataset.snow),fog:num(canvas.dataset.fog),storm:num(canvas.dataset.storm),clouds:num(canvas.dataset.clouds),wind:num(canvas.dataset.wind),temp:num(canvas.dataset.temp||20),night:num(canvas.dataset.night)};let active=true,visible=true,frame=0,last=0;const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches,fps=matchMedia('(max-width:900px),(max-height:600px)').matches?24:30,resize=()=>{const dpr=Math.min(devicePixelRatio||1,matchMedia('(max-width:900px),(max-height:600px)').matches?1:1.25),w=Math.max(1,Math.round(canvas.clientWidth*dpr)),h=Math.max(1,Math.round(canvas.clientHeight*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;gl.viewport(0,0,w,h)}},draw=now=>{if(!active||!canvas.isConnected)return;frame=requestAnimationFrame(draw);if(!visible||document.hidden||(!reduced&&now-last<1000/fps))return;last=now;resize();gl.useProgram(program);gl.bindVertexArray(vao);gl.uniform1f(loc.time,reduced?0:now);for(const name of names.slice(1))gl.uniform1f(loc[name],values[name]);gl.drawArrays(gl.TRIANGLE_STRIP,0,4);if(reduced){cancelAnimationFrame(frame);frame=0}};const io='IntersectionObserver'in window?new IntersectionObserver(e=>{visible=e[0]?.isIntersecting!==false},{rootMargin:'80px'}):null,ro='ResizeObserver'in window?new ResizeObserver(resize):null;io?.observe(canvas);ro?.observe(canvas);canvas._argusWebglStop=()=>{active=false;cancelAnimationFrame(frame);io?.disconnect();ro?.disconnect();gl.deleteBuffer(buffer);gl.deleteVertexArray(vao);gl.deleteProgram(program)};canvas.closest('.wx-atmosphere')?.classList.add('webgl-active');resize();frame=requestAnimationFrame(draw)
 };
}
