import React,{createContext,useContext,useMemo,useState}from'react';
import type {HomeAssistant}from'../core/home-assistant';

export const ARGUS_LOCALES=['es','en','fr','pt','it','zh-Hans','zh-Hant','hi','ar','ko','ja','uk']as const;
export type ArgusLocale=(typeof ARGUS_LOCALES)[number];
export const ARGUS_LOCALE_NAMES:Record<ArgusLocale,string>={
  'es':'Español',
  'en':'English',
  'fr':'Français',
  'pt':'Português',
  'it':'Italiano',
  'zh-Hans':'简体中文',
  'zh-Hant':'繁體中文',
  'hi':'हिन्दी',
  'ar':'العربية',
  'ko':'한국어',
  'ja':'日本語',
  'uk':'Українська'
};
export type I18nKey=keyof typeof es;
type Values=Record<string,string|number>;
type Catalog=Record<string,string>;
type I18n={locale:ArgusLocale;setLocale:(locale:ArgusLocale)=>void;t:(key:I18nKey,values?:Values)=>string;error:(cause:unknown)=>string};

const es={
  'app.panel':'Panel de seguridad','app.instance':'Instancia','app.language':'Idioma','app.none':'No hay instancias Argus configuradas.','app.setup':'Configura Argus','app.profile':'Selecciona un perfil','app.complete':'Completar configuración inicial',
  'widget.security':'Estado de seguridad','widget.activity':'Actividad','widget.automations':'Automatizaciones','widget.access':'Acceso y SOS','widget.alarm':'Configuración de alarma','widget.backup':'Respaldo','widget.support':'Apoya a Argus',
  'action.home':'Armar casa','action.away':'Armar fuera','action.disarm':'Desarmar','action.refresh':'Actualizar','action.export':'Exportar','action.restore':'Restaurar','action.logout':'Cerrar sesión','action.save':'Guardar','action.delete':'Eliminar','action.enable':'Activar','action.disable':'Desactivar','action.open':'Abrir en Home Assistant','action.manage':'Gestionar automatizaciones en Home Assistant','action.addProfile':'Añadir perfil','action.addRule':'Añadir regla','action.saveMode':'Guardar modo','action.saveName':'Guardar nombre','action.saveAdvanced':'Guardar controles avanzados','action.clear':'Borrar registro',
  'status.review':'Estado en revisión','status.unavailable':'no disponible','status.active':'activo','status.disabled':'desactivado','status.enabled':'Activa','status.inactive':'Desactivada','status.configured':'(configurado)','status.empty':'Sin actividad reciente','status.event':'Evento','status.incident':'Incidencia','status.open':'abierta',
  'sos.title':'Acciones SOS','sos.save':'Guardar acciones SOS','sos.saving':'Guardando…','sos.none':'No hay salidas SOS compatibles.','sos.saved':'Acciones SOS guardadas para esta instancia.','sos.permission':'Tu perfil necesita el permiso «Gestionar SOS» para guardar estas salidas.','sos.failed':'No se pudieron guardar las acciones SOS. Verifica el permiso Gestionar SOS.',
  'automation.readOnly':'Automatizaciones de Home Assistant relacionadas con esta instancia (solo lectura).','automation.empty':'No hay automatizaciones de Home Assistant relacionadas con esta instancia.','automation.noCrud':'Argus no crea ni modifica automatizaciones. Esta lista es solo de lectura para la instancia seleccionada.','automation.dashboard':'Abrir Automatizaciones de Home Assistant',
  'admin.title':'Administración avanzada','admin.users':'Usuarios, PIN y presencia','admin.modes':'Modos, sensores y sirenas','admin.automations':'Automatizaciones de Home Assistant','admin.personalization':'Personalización multimedia y temas','admin.forensics':'Incidencias y forense','admin.advanced':'Configuración avanzada','admin.profiles':'Perfiles y permisos','admin.presence':'Presencia','admin.incidents':'Incidencias','admin.audit':'Auditoría',
  'field.name':'Nombre','field.rule':'Nombre de regla','field.home':'Nombre del hogar','field.noHa':'Sin cuenta HA','field.standard':'Estándar','field.admin':'Administrador','field.arming':'Retardo de armado (segundos)','field.entry':'Retardo de entrada (segundos)','field.closed':'Exigir sensores cerrados antes de armar','field.mqtt':'Publicar estado MQTT','field.people':'Personas que activan la regla','field.sensors':'Sensores activos','field.bypassed':'Sensores en bypass','field.entrySensors':'Sensores con retraso de entrada','field.sirens':'Sirenas y salidas','field.panels':'Paneles externos','field.lights':'Luces de alarma','field.lightOptions':'Color y destello de luces de alarma','field.color':'Color de {entity}','field.noFlash':'Sin destello','field.gentle':'Destello suave','field.rapid':'Destello rápido','field.background':'Argus usa un único fondo predeterminado fijo. Los fondos personalizados y el clima animado no se ejecutan ni se guardan.','field.codes':'Los códigos existentes no se exponen. Escribe un valor sólo para sustituirlo; deja el campo vacío para conservarlo.','field.armCode':'Requerir código para armar','field.guest':'Habilitar código de invitado','field.newGuest':'Nuevo código de invitado','field.duress':'PIN de coacción {configured}',
  'dashboard.loading':'Cargando tablero…','dashboard.edit':'✥ Editar tablero','dashboard.done':'✓ Listo','dashboard.reset':'Restablecer diseño','dashboard.resetWidget':'Restablecer widget','dashboard.hide':'Ocultar widget','dashboard.size':'Tamaño','dashboard.options':'Opciones','dashboard.drag':'Arrastrar para mover','dashboard.move':'Mover {widget}','dashboard.hidden':'Widgets ocultos','dashboard.show':'Mostrar {widget}','dashboard.finished':'Edición finalizada','dashboard.restored':'Diseño predeterminado restaurado','dashboard.saved':'Posición guardada','dashboard.blocked':'Posición bloqueada por colisión','dashboard.resized':'Tamaño {size}','dashboard.widgetRestored':'Widget restablecido','dashboard.visible':'Widget visible','dashboard.invisible':'Widget oculto','dashboard.confirm':'¿Restablecer únicamente posiciones, tamaños y visibilidad del tablero?','dashboard.toolbar':'Edición del tablero',
  'profile.active':'Perfil activo: {name}','profile.accessPin':'PIN de acceso para {name}','profile.removePin':'PIN para {name}; vacío elimina','profile.adminName':'Nombre del administrador Argus','profile.disarmPin':'PIN de desarmado (si aplica)',
  'error.unknown':'Se produjo un error inesperado.','error.permission':'No tienes permiso para realizar esta acción.','error.notFound':'No se encontró la instancia de Argus.','error.light':'La luz seleccionada no está disponible en Home Assistant.','error.background':'Argus utiliza un fondo predeterminado fijo.','error.widgetTitle':'⚠️ Error del widget','error.widgetBody':'No se pudo renderizar un componente.',
  'activity.armed':'Sistema armado','activity.disarmed':'Sistema desarmado','activity.cancelled':'Armado cancelado','activity.rejected':'Armado rechazado','activity.restored':'Configuración restaurada','activity.cleared':'Registro de auditoría borrado','activity.automation':'Automatización ejecutada','activity.updated':'Configuración actualizada','activity.historic':'Evento histórico'
}as const;

const en:Catalog={
  'app.panel':'Security panel','app.instance':'Instance','app.language':'Language','app.none':'No Argus instances are configured.','app.setup':'Set up Argus','app.profile':'Select a profile','app.complete':'Complete initial setup',
  'widget.security':'Security status','widget.activity':'Activity','widget.automations':'Automations','widget.access':'Access and SOS','widget.alarm':'Alarm configuration','widget.backup':'Backup','widget.support':'Support Argus',
  'action.home':'Arm home','action.away':'Arm away','action.disarm':'Disarm','action.refresh':'Refresh','action.export':'Export','action.restore':'Restore','action.logout':'Sign out','action.save':'Save','action.delete':'Delete','action.enable':'Enable','action.disable':'Disable','action.open':'Open in Home Assistant','action.manage':'Manage automations in Home Assistant','action.addProfile':'Add profile','action.addRule':'Add rule','action.saveMode':'Save mode','action.saveName':'Save name','action.saveAdvanced':'Save advanced controls','action.clear':'Clear log',
  'status.review':'Status under review','status.unavailable':'unavailable','status.active':'active','status.disabled':'disabled','status.enabled':'Enabled','status.inactive':'Disabled','status.configured':'(configured)','status.empty':'No recent activity','status.event':'Event','status.incident':'Incident','status.open':'open',
  'sos.title':'SOS actions','sos.save':'Save SOS actions','sos.saving':'Saving…','sos.none':'No compatible SOS outputs.','sos.saved':'SOS actions saved for this instance.','sos.permission':'Your profile needs the “Manage SOS” permission to save these outputs.','sos.failed':'Could not save SOS actions. Check the Manage SOS permission.',
  'automation.readOnly':'Home Assistant automations related to this instance (read-only).','automation.empty':'No Home Assistant automations are related to this instance.','automation.noCrud':'Argus does not create or modify automations. This list is read-only for the selected instance.','automation.dashboard':'Open Home Assistant Automations',
  'admin.title':'Advanced administration','admin.users':'Users, PIN and presence','admin.modes':'Modes, sensors and sirens','admin.automations':'Home Assistant automations','admin.personalization':'Multimedia and themes','admin.forensics':'Incidents and forensics','admin.advanced':'Advanced configuration','admin.profiles':'Profiles and permissions','admin.presence':'Presence','admin.incidents':'Incidents','admin.audit':'Audit',
  'field.name':'Name','field.rule':'Rule name','field.home':'Home name','field.noHa':'No HA account','field.standard':'Standard','field.admin':'Administrator','field.arming':'Arming delay (seconds)','field.entry':'Entry delay (seconds)','field.closed':'Require closed sensors before arming','field.mqtt':'Publish MQTT status','field.people':'People that trigger the rule','field.sensors':'Active sensors','field.bypassed':'Bypassed sensors','field.entrySensors':'Sensors with entry delay','field.sirens':'Sirens and outputs','field.panels':'External panels','field.lights':'Alarm lights','field.lightOptions':'Alarm light colour and flash','field.color':'Colour for {entity}','field.noFlash':'No flash','field.gentle':'Gentle flash','field.rapid':'Rapid flash','field.background':'Argus uses one fixed default background. Custom backgrounds and animated weather do not run or persist.','field.codes':'Existing codes are not displayed. Enter a value only to replace it; leave it empty to keep it.','field.armCode':'Require a code to arm','field.guest':'Enable guest code','field.newGuest':'New guest code','field.duress':'Duress PIN {configured}',
  'dashboard.loading':'Loading dashboard…','dashboard.edit':'✥ Edit dashboard','dashboard.done':'✓ Done','dashboard.reset':'Reset layout','dashboard.resetWidget':'Reset widget','dashboard.hide':'Hide widget','dashboard.size':'Size','dashboard.options':'Options','dashboard.drag':'Drag to move','dashboard.move':'Move {widget}','dashboard.hidden':'Hidden widgets','dashboard.show':'Show {widget}','dashboard.finished':'Editing finished','dashboard.restored':'Default layout restored','dashboard.saved':'Position saved','dashboard.blocked':'Position blocked by collision','dashboard.resized':'Size {size}','dashboard.widgetRestored':'Widget restored','dashboard.visible':'Widget visible','dashboard.invisible':'Widget hidden','dashboard.confirm':'Reset only the dashboard positions, sizes, and visibility?','dashboard.toolbar':'Dashboard editing',
  'profile.active':'Active profile: {name}','profile.accessPin':'Access PIN for {name}','profile.removePin':'PIN for {name}; leave empty to remove','profile.adminName':'Argus administrator name','profile.disarmPin':'Disarm PIN (if applicable)',
  'error.unknown':'An unexpected error occurred.','error.permission':'You do not have permission to perform this action.','error.notFound':'Argus instance was not found.','error.light':'The selected light is not available in Home Assistant.','error.background':'Argus uses a fixed default background.','error.widgetTitle':'⚠️ Widget error','error.widgetBody':'A component could not be rendered.',
  'activity.armed':'System armed','activity.disarmed':'System disarmed','activity.cancelled':'Arming cancelled','activity.rejected':'Arming rejected','activity.restored':'Configuration restored','activity.cleared':'Audit log cleared','activity.automation':'Automation executed','activity.updated':'Configuration updated','activity.historic':'Historical event'
};

const fr:Catalog={
  'app.panel':'Panneau de sécurité','app.instance':'Instance','app.language':'Langue','app.none':'Aucune instance Argus n’est configurée.','app.setup':'Configurer Argus','app.profile':'Sélectionnez un profil','app.complete':'Terminer la configuration initiale',
  'widget.security':'État de sécurité','widget.activity':'Activité','widget.automations':'Automatisations','widget.access':'Accès et SOS','widget.alarm':'Configuration de l’alarme','widget.backup':'Sauvegarde','widget.support':'Soutenir Argus',
  'action.home':'Armer à domicile','action.away':'Armer à l’extérieur','action.disarm':'Désarmer','action.refresh':'Actualiser','action.export':'Exporter','action.restore':'Restaurer','action.logout':'Se déconnecter','action.save':'Enregistrer','action.delete':'Supprimer','action.enable':'Activer','action.disable':'Désactiver','action.open':'Ouvrir dans Home Assistant','action.manage':'Gérer les automatisations dans Home Assistant','action.addProfile':'Ajouter un profil','action.addRule':'Ajouter une règle','action.saveMode':'Enregistrer le mode','action.saveName':'Enregistrer le nom','action.saveAdvanced':'Enregistrer les paramètres avancés','action.clear':'Effacer le journal',
  'status.review':'État en cours d’examen','status.unavailable':'indisponible','status.active':'actif','status.disabled':'désactivé','status.enabled':'Activée','status.inactive':'Désactivée','status.configured':'(configuré)','status.empty':'Aucune activité récente','status.event':'Événement','status.incident':'Incident','status.open':'ouvert',
  'sos.title':'Actions SOS','sos.save':'Enregistrer les actions SOS','sos.saving':'Enregistrement…','sos.none':'Aucune sortie SOS compatible.','sos.saved':'Actions SOS enregistrées pour cette instance.','sos.permission':'Votre profil nécessite la permission « Gérer SOS » pour enregistrer ces sorties.','sos.failed':'Impossible d’enregistrer les actions SOS. Vérifiez la permission Gérer SOS.',
  'automation.readOnly':'Automatisations Home Assistant associées à cette instance (lecture seule).','automation.empty':'Aucune automatisation Home Assistant n’est associée à cette instance.','automation.noCrud':'Argus ne crée ni ne modifie d’automatisations. Cette liste est en lecture seule pour l’instance sélectionnée.','automation.dashboard':'Ouvrir les Automatisations Home Assistant',
  'admin.title':'Administration avancée','admin.users':'Utilisateurs, PIN et présence','admin.modes':'Modes, capteurs et sirènes','admin.automations':'Automatisations Home Assistant','admin.personalization':'Multimédia et thèmes','admin.forensics':'Incidents et criminalistique','admin.advanced':'Configuration avancée','admin.profiles':'Profils et permissions','admin.presence':'Présence','admin.incidents':'Incidents','admin.audit':'Audit',
  'field.name':'Nom','field.rule':'Nom de la règle','field.home':'Nom du domicile','field.noHa':'Aucun compte HA','field.standard':'Standard','field.admin':'Administrateur','field.arming':'Délai d’armement (secondes)','field.entry':'Délai d’entrée (secondes)','field.closed':'Exiger la fermeture des capteurs avant l’armement','field.mqtt':'Publier l’état MQTT','field.people':'Personnes déclenchant la règle','field.sensors':'Capteurs actifs','field.bypassed':'Capteurs contournés','field.entrySensors':'Capteurs avec délai d’entrée','field.sirens':'Sirènes et sorties','field.panels':'Panneaux externes','field.lights':'Lumières d’alarme','field.lightOptions':'Couleur et clignotement des lumières','field.color':'Couleur de {entity}','field.noFlash':'Sans clignotement','field.gentle':'Clignotement doux','field.rapid':'Clignotement rapide','field.background':'Argus utilise un arrière-plan fixe par défaut. Les fonds personnalisés et la météo animée ne sont pas exécutés ni enregistrés.','field.codes':'Les codes existants ne sont pas affichés. Saisissez une valeur uniquement pour la remplacer ; laissez vide pour la conserver.','field.armCode':'Exiger un code pour armer','field.guest':'Activer le code invité','field.newGuest':'Nouveau code invité','field.duress':'PIN sous contrainte {configured}',
  'dashboard.loading':'Chargement du tableau de bord…','dashboard.edit':'✥ Modifier le tableau','dashboard.done':'✓ Terminé','dashboard.reset':'Réinitialiser la disposition','dashboard.resetWidget':'Réinitialiser le widget','dashboard.hide':'Masquer le widget','dashboard.size':'Taille','dashboard.options':'Options','dashboard.drag':'Faire glisser pour déplacer','dashboard.move':'Déplacer {widget}','dashboard.hidden':'Widgets masqués','dashboard.show':'Afficher {widget}','dashboard.finished':'Modification terminée','dashboard.restored':'Disposition par défaut restaurée','dashboard.saved':'Position enregistrée','dashboard.blocked':'Position bloquée par collision','dashboard.resized':'Taille {size}','dashboard.widgetRestored':'Widget réinitialisé','dashboard.visible':'Widget visible','dashboard.invisible':'Widget masqué','dashboard.confirm':'Réinitialiser uniquement les positions, tailles et visibilité du tableau ?','dashboard.toolbar':'Édition du tableau de bord',
  'profile.active':'Profil actif : {name}','profile.accessPin':'PIN d’accès pour {name}','profile.removePin':'PIN pour {name} ; laisser vide pour supprimer','profile.adminName':'Nom de l’administrateur Argus','profile.disarmPin':'PIN de désarmement (si applicable)',
  'error.unknown':'Une erreur inattendue est survenue.','error.permission':'Vous n’avez pas la permission d’effectuer cette action.','error.notFound':'L’instance Argus est introuvable.','error.light':'La lumière sélectionnée n’est pas disponible dans Home Assistant.','error.background':'Argus utilise un arrière-plan par défaut fixe.','error.widgetTitle':'⚠️ Erreur du widget','error.widgetBody':'Impossible de restituer un composant.',
  'activity.armed':'Système armé','activity.disarmed':'Système désarmé','activity.cancelled':'Armement annulé','activity.rejected':'Armement rejeté','activity.restored':'Configuration restaurée','activity.cleared':'Journal d’audit effacé','activity.automation':'Automatisation exécutée','activity.updated':'Configuration mise à jour','activity.historic':'Événement historique'
};

const pt:Catalog={
  'app.panel':'Painel de segurança','app.instance':'Instância','app.language':'Idioma','app.none':'Nenhuma instância Argus está configurada.','app.setup':'Configurar Argus','app.profile':'Selecione um perfil','app.complete':'Concluir configuração inicial',
  'widget.security':'Estado de segurança','widget.activity':'Atividade','widget.automations':'Automações','widget.access':'Acesso e SOS','widget.alarm':'Configuração do alarme','widget.backup':'Backup','widget.support':'Apoie o Argus',
  'action.home':'Armar em casa','action.away':'Armar fora','action.disarm':'Desarmar','action.refresh':'Atualizar','action.export':'Exportar','action.restore':'Restaurar','action.logout':'Sair','action.save':'Salvar','action.delete':'Excluir','action.enable':'Ativar','action.disable':'Desativar','action.open':'Abrir no Home Assistant','action.manage':'Gerenciar automações no Home Assistant','action.addProfile':'Adicionar perfil','action.addRule':'Adicionar regra','action.saveMode':'Salvar modo','action.saveName':'Salvar nome','action.saveAdvanced':'Salvar controles avançados','action.clear':'Limpar registro',
  'status.review':'Estado em revisão','status.unavailable':'indisponível','status.active':'ativo','status.disabled':'desativado','status.enabled':'Ativada','status.inactive':'Desativada','status.configured':'(configurado)','status.empty':'Sem atividade recente','status.event':'Evento','status.incident':'Incidente','status.open':'aberto',
  'sos.title':'Ações SOS','sos.save':'Salvar ações SOS','sos.saving':'Salvando…','sos.none':'Nenhuma saída SOS compatível.','sos.saved':'Ações SOS salvas para esta instância.','sos.permission':'Seu perfil precisa da permissão “Gerenciar SOS” para salvar essas saídas.','sos.failed':'Não foi possível salvar as ações SOS. Verifique a permissão Gerenciar SOS.',
  'automation.readOnly':'Automações do Home Assistant relacionadas a esta instância (somente leitura).','automation.empty':'Nenhuma automação do Home Assistant relacionada a esta instância.','automation.noCrud':'O Argus não cria nem edita automações. Esta lista é apenas para leitura da instância selecionada.','automation.dashboard':'Abrir Automações do Home Assistant',
  'admin.title':'Administração avançada','admin.users':'Usuários, PIN e presença','admin.modes':'Modos, sensores e sirenes','admin.automations':'Automações do Home Assistant','admin.personalization':'Multimídia e temas','admin.forensics':'Incidentes e perícia','admin.advanced':'Configuração avançada','admin.profiles':'Perfis e permissões','admin.presence':'Presença','admin.incidents':'Incidentes','admin.audit':'Auditoria',
  'field.name':'Nome','field.rule':'Nome da regra','field.home':'Nome da casa','field.noHa':'Sem conta HA','field.standard':'Padrão','field.admin':'Administrador','field.arming':'Atraso de armação (segundos)','field.entry':'Atraso de entrada (segundos)','field.closed':'Exigir sensores fechados antes de armar','field.mqtt':'Publicar estado MQTT','field.people':'Pessoas que acionam a regra','field.sensors':'Sensores ativos','field.bypassed':'Sensores ignorados (bypass)','field.entrySensors':'Sensores com atraso de entrada','field.sirens':'Sirenes e saídas','field.panels':'Painéis externos','field.lights':'Luzes de alarme','field.lightOptions':'Cor e intermitência das luzes','field.color':'Cor de {entity}','field.noFlash':'Sem piscar','field.gentle':'Piscar suave','field.rapid':'Piscar rápido','field.background':'O Argus utiliza um plano de fundo padrão fixo. Planos de fundo personalizados e clima animado não são executados nem salvos.','field.codes':'Códigos existentes não são exibidos. Digite um valor apenas para substituí-lo; deixe em branco para manter.','field.armCode':'Exigir código para armar','field.guest':'Habilitar código de convidado','field.newGuest':'Novo código de convidado','field.duress':'PIN de coação {configured}',
  'dashboard.loading':'Carregando painel…','dashboard.edit':'✥ Editar painel','dashboard.done':'✓ Concluído','dashboard.reset':'Redefinir layout','dashboard.resetWidget':'Redefinir widget','dashboard.hide':'Ocultar widget','dashboard.size':'Tamanho','dashboard.options':'Opções','dashboard.drag':'Arrastar para mover','dashboard.move':'Mover {widget}','dashboard.hidden':'Widgets ocultos','dashboard.show':'Mostrar {widget}','dashboard.finished':'Edição concluída','dashboard.restored':'Layout padrão restaurado','dashboard.saved':'Posição salva','dashboard.blocked':'Posição bloqueada por colisão','dashboard.resized':'Tamanho {size}','dashboard.widgetRestored':'Widget redefinido','dashboard.visible':'Widget visível','dashboard.invisible':'Widget oculto','dashboard.confirm':'Redefinir apenas posições, tamanhos e visibilidade do painel?','dashboard.toolbar':'Edição do painel',
  'profile.active':'Perfil ativo: {name}','profile.accessPin':'PIN de acesso para {name}','profile.removePin':'PIN para {name}; deixe vazio para remover','profile.adminName':'Nome do administrador Argus','profile.disarmPin':'PIN de desarmar (se aplicável)',
  'error.unknown':'Ocorreu um erro inesperado.','error.permission':'Você não tem permissão para realizar esta ação.','error.notFound':'Instância do Argus não encontrada.','error.light':'A luz selecionada não está disponível no Home Assistant.','error.background':'O Argus usa um plano de fundo padrão fixo.','error.widgetTitle':'⚠️ Erro no widget','error.widgetBody':'Não foi possível renderizar um componente.',
  'activity.armed':'Sistema armado','activity.disarmed':'Sistema desarmado','activity.cancelled':'Armação cancelada','activity.rejected':'Armação rejeitada','activity.restored':'Configuração restaurada','activity.cleared':'Registro de auditoria limpo','activity.automation':'Automação executada','activity.updated':'Configuração atualizada','activity.historic':'Evento histórico'
};

const it:Catalog={
  'app.panel':'Pannello di sicurezza','app.instance':'Istanza','app.language':'Lingua','app.none':'Nessuna istanza Argus è configurata.','app.setup':'Configura Argus','app.profile':'Seleziona un profilo','app.complete':'Completa configurazione iniziale',
  'widget.security':'Stato di sicurezza','widget.activity':'Attività','widget.automations':'Automazioni','widget.access':'Accesso e SOS','widget.alarm':'Configurazione allarme','widget.backup':'Backup','widget.support':'Sostieni Argus',
  'action.home':'Inserisci a casa','action.away':'Inserisci fuori casa','action.disarm':'Disinserisci','action.refresh':'Aggiorna','action.export':'Esporta','action.restore':'Ripristina','action.logout':'Esci','action.save':'Salva','action.delete':'Elimina','action.enable':'Attiva','action.disable':'Disattiva','action.open':'Apri in Home Assistant','action.manage':'Gestisci automazioni in Home Assistant','action.addProfile':'Aggiungi profilo','action.addRule':'Aggiungi regola','action.saveMode':'Salva modalità','action.saveName':'Salva nome','action.saveAdvanced':'Salva impostazioni avanzate','action.clear':'Cancella registro',
  'status.review':'Stato in revisione','status.unavailable':'non disponibile','status.active':'attivo','status.disabled':'disattivato','status.enabled':'Attiva','status.inactive':'Disattivata','status.configured':'(configurato)','status.empty':'Nessuna attività recente','status.event':'Evento','status.incident':'Incidente','status.open':'aperto',
  'sos.title':'Azioni SOS','sos.save':'Salva azioni SOS','sos.saving':'Salvataggio…','sos.none':'Nessuna uscita SOS compatibile.','sos.saved':'Azioni SOS salvate per questa istanza.','sos.permission':'Il tuo profilo necessita del permesso «Gestisci SOS» per salvare queste uscite.','sos.failed':'Impossibile salvare le azioni SOS. Verifica il permesso Gestisci SOS.',
  'automation.readOnly':'Automazioni Home Assistant correlate a questa istanza (sola lettura).','automation.empty':'Nessuna automazione Home Assistant correlata a questa istanza.','automation.noCrud':'Argus non crea né modifica automazioni. Questo elenco è in sola lettura per l’istanza selezionata.','automation.dashboard':'Apri Automazioni di Home Assistant',
  'admin.title':'Amministrazione avanzata','admin.users':'Utenti, PIN e presenza','admin.modes':'Modalità, sensori e sirene','admin.automations':'Automazioni Home Assistant','admin.personalization':'Contenuti multimediali e temi','admin.forensics':'Incidenti e perizia','admin.advanced':'Configurazione avanzata','admin.profiles':'Profili e permessi','admin.presence':'Presenza','admin.incidents':'Incidenti','admin.audit':'Audit',
  'field.name':'Nome','field.rule':'Nome della regola','field.home':'Nome della casa','field.noHa':'Nessun account HA','field.standard':'Standard','field.admin':'Amministratore','field.arming':'Ritardo inserimento (secondi)','field.entry':'Ritardo ingresso (secondi)','field.closed':'Richiedi sensori chiusi prima di inserire','field.mqtt':'Pubblica stato MQTT','field.people':'Persone che attivano la regola','field.sensors':'Sensori attivi','field.bypassed':'Sensori esclusi (bypass)','field.entrySensors':'Sensori con ritardo ingresso','field.sirens':'Sirene e uscite','field.panels':'Pannelli esterni','field.lights':'Luci di allarme','field.lightOptions':'Colore e lampeggio delle luci','field.color':'Colore di {entity}','field.noFlash':'Nessun lampeggio','field.gentle':'Lampeggio delicato','field.rapid':'Lampeggio rapido','field.background':'Argus utilizza un unico sfondo predefinito fisso. Sfondi personalizzati e meteo animato non sono supportati né salvati.','field.codes':'I codici esistenti non vengono mostrati. Inserisci un valore solo per sostituirlo; lascia vuoto per conservare.','field.armCode':'Richiedi codice per inserire','field.guest':'Abilita codice ospite','field.newGuest':'Nuovo codice ospite','field.duress':'PIN di coercizione {configured}',
  'dashboard.loading':'Caricamento dashboard…','dashboard.edit':'✥ Modifica dashboard','dashboard.done':'✓ Fatto','dashboard.reset':'Reimposta layout','dashboard.resetWidget':'Reimposta widget','dashboard.hide':'Nascondi widget','dashboard.size':'Dimensione','dashboard.options':'Opzioni','dashboard.drag':'Trascina per spostare','dashboard.move':'Sposta {widget}','dashboard.hidden':'Widget nascosti','dashboard.show':'Mostra {widget}','dashboard.finished':'Modifica terminata','dashboard.restored':'Layout predefinito ripristinato','dashboard.saved':'Posizione salvata','dashboard.blocked':'Posizione bloccata da collisione','dashboard.resized':'Dimensione {size}','dashboard.widgetRestored':'Widget reimpostato','dashboard.visible':'Widget visibile','dashboard.invisible':'Widget nascosto','dashboard.confirm':'Reimpostare solo posizioni, dimensioni e visibilità della dashboard?','dashboard.toolbar':'Modifica della dashboard',
  'profile.active':'Profilo attivo: {name}','profile.accessPin':'PIN di accesso per {name}','profile.removePin':'PIN per {name}; lascia vuoto per eliminare','profile.adminName':'Nome dell’amministratore Argus','profile.disarmPin':'PIN di disinserimento (se applicabile)',
  'error.unknown':'Si è verificato un errore imprevisto.','error.permission':'Non hai il permesso di eseguire questa azione.','error.notFound':'Istanza Argus non trovata.','error.light':'La luce selezionata non è disponibile in Home Assistant.','error.background':'Argus utilizza uno sfondo predefinito fisso.','error.widgetTitle':'⚠️ Errore del widget','error.widgetBody':'Impossibile visualizzare un componente.',
  'activity.armed':'Sistema inserito','activity.disarmed':'Sistema disinserito','activity.cancelled':'Inserimento annullato','activity.rejected':'Inserimento rifiutato','activity.restored':'Configurazione ripristinata','activity.cleared':'Registro audit cancellato','activity.automation':'Automazione eseguita','activity.updated':'Configurazione aggiornata','activity.historic':'Evento storico'
};

const zhHans:Catalog={
  'app.panel':'安全面板','app.instance':'实例','app.language':'语言','app.none':'未配置 Argus 实例。','app.setup':'设置 Argus','app.profile':'选择配置文件','app.complete':'完成初始设置',
  'widget.security':'安全状态','widget.activity':'活动','widget.automations':'自动化','widget.access':'访问和 SOS','widget.alarm':'警报配置','widget.backup':'备份','widget.support':'支持 Argus',
  'action.home':'在家布防','action.away':'外出布防','action.disarm':'撤防','action.refresh':'刷新','action.export':'导出','action.restore':'恢复','action.logout':'退出登录','action.save':'保存','action.delete':'删除','action.enable':'启用','action.disable':'停用','action.open':'在 Home Assistant 中打开','action.manage':'在 Home Assistant 中管理自动化','action.addProfile':'添加用户档案','action.addRule':'添加规则','action.saveMode':'保存模式','action.saveName':'保存名称','action.saveAdvanced':'保存高级控制','action.clear':'清除日志',
  'status.review':'状态审核中','status.unavailable':'不可用','status.active':'已启用','status.disabled':'已停用','status.enabled':'已启用','status.inactive':'已停用','status.configured':'(已配置)','status.empty':'没有最近活动','status.event':'事件','status.incident':'事故','status.open':'开启',
  'sos.title':'SOS 紧急动作','sos.save':'保存 SOS 动作','sos.saving':'正在保存…','sos.none':'没有兼容的 SOS 输出。','sos.saved':'已为此实例保存 SOS 动作。','sos.permission':'您的档案需要“管理 SOS”权限才能保存这些输出。','sos.failed':'无法保存 SOS 动作。请检查管理 SOS 权限。',
  'automation.readOnly':'与此实例相关的 Home Assistant 自动化（只读）。','automation.empty':'没有与此实例相关的 Home Assistant 自动化。','automation.noCrud':'Argus 不创建或修改自动化。此列表针对所选实例为只读。','automation.dashboard':'打开 Home Assistant 自动化面板',
  'admin.title':'高级管理','admin.users':'用户、PIN 和在家状态','admin.modes':'模式、传感器和警报器','admin.automations':'Home Assistant 自动化','admin.personalization':'多媒体与主题','admin.forensics':'事故与取证','admin.advanced':'高级配置','admin.profiles':'档案与权限','admin.presence':'在场规则','admin.incidents':'事故记录','admin.audit':'审计日志',
  'field.name':'名称','field.rule':'规则名称','field.home':'家庭名称','field.noHa':'无 HA 账号','field.standard':'标准用户','field.admin':'管理员','field.arming':'布防延迟 (秒)','field.entry':'进入延迟 (秒)','field.closed':'布防前要求传感器处于关闭状态','field.mqtt':'发布 MQTT 状态','field.people':'触发规则的人员','field.sensors':'活动传感器','field.bypassed':'旁路传感器','field.entrySensors':'具有进入延迟的传感器','field.sirens':'警报器与输出','field.panels':'外部面板','field.lights':'警报灯光','field.lightOptions':'警报灯光颜色与闪烁','field.color':'{entity} 的颜色','field.noFlash':'无闪烁','field.gentle':'柔和闪烁','field.rapid':'快速闪烁','field.background':'Argus 使用固定的默认背景。不支持或保存自定义背景与动态天气。','field.codes':'现有密码不会显示。仅在需要替换时输入值；留空表示保留原值。','field.armCode':'布防需要密码','field.guest':'启用访客密码','field.newGuest':'新访客密码','field.duress':'胁迫 PIN {configured}',
  'dashboard.loading':'正在加载仪表板…','dashboard.edit':'✥ 编辑仪表板','dashboard.done':'✓ 完成','dashboard.reset':'重置布局','dashboard.resetWidget':'重置组件','dashboard.hide':'隐藏组件','dashboard.size':'尺寸','dashboard.options':'选项','dashboard.drag':'拖动以移动','dashboard.move':'移动 {widget}','dashboard.hidden':'隐藏的组件','dashboard.show':'显示 {widget}','dashboard.finished':'编辑已完成','dashboard.restored':'已恢复默认布局','dashboard.saved':'位置已保存','dashboard.blocked':'位置因重叠碰撞受阻','dashboard.resized':'尺寸已调整为 {size}','dashboard.widgetRestored':'组件已重置','dashboard.visible':'组件已显示','dashboard.invisible':'组件已隐藏','dashboard.confirm':'仅重置仪表板的位置、大小和可见性？','dashboard.toolbar':'仪表板编辑工具栏',
  'profile.active':'当前档案: {name}','profile.accessPin':'{name} 的访问 PIN','profile.removePin':'{name} 的 PIN；留空则删除','profile.adminName':'Argus 管理员名称','profile.disarmPin':'撤防 PIN (如适用)',
  'error.unknown':'发生意外错误。','error.permission':'您无权执行此操作。','error.notFound':'未找到 Argus 实例。','error.light':'所选灯光在 Home Assistant 中不可用。','error.background':'Argus 使用固定的默认背景。','error.widgetTitle':'⚠️ 组件错误','error.widgetBody':'无法渲染该组件。',
  'activity.armed':'系统已布防','activity.disarmed':'系统已撤防','activity.cancelled':'布防已取消','activity.rejected':'布防被拒绝','activity.restored':'配置已恢复','activity.cleared':'审计日志已清除','activity.automation':'自动化已执行','activity.updated':'配置已更新','activity.historic':'历史事件'
};

const zhHant:Catalog={
  'app.panel':'安全面板','app.instance':'執行個體','app.language':'語言','app.none':'未設定 Argus 執行個體。','app.setup':'設定 Argus','app.profile':'選取設定檔','app.complete':'完成初始設定',
  'widget.security':'安全狀態','widget.activity':'活動','widget.automations':'自動化','widget.access':'存取與 SOS','widget.alarm':'警報設定','widget.backup':'備份','widget.support':'支持 Argus',
  'action.home':'在家佈防','action.away':'外出佈防','action.disarm':'解除警戒','action.refresh':'重新整理','action.export':'匯出','action.restore':'還原','action.logout':'登出','action.save':'儲存','action.delete':'刪除','action.enable':'啟用','action.disable':'停用','action.open':'在 Home Assistant 中開啟','action.manage':'在 Home Assistant 中管理自動化','action.addProfile':'新增設定檔','action.addRule':'新增規則','action.saveMode':'儲存模式','action.saveName':'儲存名稱','action.saveAdvanced':'儲存進階控制','action.clear':'清除記錄',
  'status.review':'狀態審核中','status.unavailable':'無法使用','status.active':'使用中','status.disabled':'已停用','status.enabled':'已啟用','status.inactive':'已停用','status.configured':'(已設定)','status.empty':'沒有近期活動','status.event':'事件','status.incident':'事故','status.open':'開啟',
  'sos.title':'SOS 緊急動作','sos.save':'儲存 SOS 動作','sos.saving':'正在儲存…','sos.none':'沒有相容的 SOS 輸出。','sos.saved':'已為此執行個體儲存 SOS 動作。','sos.permission':'您的設定檔需要「管理 SOS」權限才能儲存這些輸出。','sos.failed':'無法儲存 SOS 動作。請檢查管理 SOS 權限。',
  'automation.readOnly':'與此執行個體關聯的 Home Assistant 自動化（唯讀）。','automation.empty':'沒有與此執行個體關聯的 Home Assistant 自動化。','automation.noCrud':'Argus 不會建立或修改自動化。此清單對所選執行個體為唯讀。','automation.dashboard':'開啟 Home Assistant 自動化面板',
  'admin.title':'進階管理','admin.users':'使用者、PIN 與在家狀態','admin.modes':'模式、感測器與警報器','admin.automations':'Home Assistant 自動化','admin.personalization':'多媒體與佈景主題','admin.forensics':'事故與鑑識','admin.advanced':'進階設定','admin.profiles':'設定檔與權限','admin.presence':'在場規則','admin.incidents':'事故記錄','admin.audit':'稽核記錄',
  'field.name':'名稱','field.rule':'規則名稱','field.home':'住家名稱','field.noHa':'無 HA 帳號','field.standard':'一般使用者','field.admin':'管理員','field.arming':'佈防延遲 (秒)','field.entry':'進入延遲 (秒)','field.closed':'佈防前要求感測器處於關閉狀態','field.mqtt':'發布 MQTT 狀態','field.people':'觸發規則的人員','field.sensors':'使用中感測器','field.bypassed':'略過 (Bypass) 感測器','field.entrySensors':'具備進入延遲的感測器','field.sirens':'警報器與輸出','field.panels':'外部面板','field.lights':'警報燈光','field.lightOptions':'警報燈光顏色與閃爍','field.color':'{entity} 的顏色','field.noFlash':'不閃爍','field.gentle':'緩和閃爍','field.rapid':'快速閃爍','field.background':'Argus 使用固定的預設背景。不支援或儲存自訂背景與動態天氣。','field.codes':'現有代碼不會顯示。僅在需取代時輸入；留空表示保留原值。','field.armCode':'佈防需要代碼','field.guest':'啟用訪客代碼','field.newGuest':'新訪客代碼','field.duress':'脅迫 PIN {configured}',
  'dashboard.loading':'正在載入儀表板…','dashboard.edit':'✥ 編輯儀表板','dashboard.done':'✓ 完成','dashboard.reset':'重設版面配置','dashboard.resetWidget':'重設小工具','dashboard.hide':'隱藏小工具','dashboard.size':'尺寸','dashboard.options':'選項','dashboard.drag':'拖曳以移動','dashboard.move':'移動 {widget}','dashboard.hidden':'隱藏的小工具','dashboard.show':'顯示 {widget}','dashboard.finished':'編輯已完成','dashboard.restored':'已還原預設版面配置','dashboard.saved':'位置已儲存','dashboard.blocked':'位置因重疊碰撞受阻','dashboard.resized':'尺寸已調整為 {size}','dashboard.widgetRestored':'小工具已重設','dashboard.visible':'小工具已顯示','dashboard.invisible':'小工具已隱藏','dashboard.confirm':'僅重設儀表板的位置、大小與可見度？','dashboard.toolbar':'儀表板編輯工具列',
  'profile.active':'使用中設定檔: {name}','profile.accessPin':'{name} 的存取 PIN','profile.removePin':'{name} 的 PIN；留空則移除','profile.adminName':'Argus 管理員名稱','profile.disarmPin':'解除警戒 PIN (如適用)',
  'error.unknown':'發生未預期的錯誤。','error.permission':'您沒有權限執行此操作。','error.notFound':'找不到 Argus 執行個體。','error.light':'所選燈光在 Home Assistant 中無法使用。','error.background':'Argus 使用固定的預設背景。','error.widgetTitle':'⚠️ 小工具錯誤','error.widgetBody':'無法轉譯該元件。',
  'activity.armed':'系統已佈防','activity.disarmed':'系統已解除警戒','activity.cancelled':'佈防已取消','activity.rejected':'佈防遭拒絕','activity.restored':'設定已還原','activity.cleared':'稽核記錄已清除','activity.automation':'自動化已執行','activity.updated':'設定已更新','activity.historic':'歷史事件'
};

const hi:Catalog={
  'app.panel':'सुरक्षा पैनल','app.instance':'इंस्टेंस','app.language':'भाषा','app.none':'कोई Argus इंस्टेंस कॉन्फ़िगर नहीं है।','app.setup':'Argus सेट करें','app.profile':'प्रोफ़ाइल चुनें','app.complete':'प्रारंभिक सेटअप पूरा करें',
  'widget.security':'सुरक्षा स्थिति','widget.activity':'गतिविधि','widget.automations':'स्वचालन','widget.access':'पहुँच और SOS','widget.alarm':'अलार्म कॉन्फ़िगरेशन','widget.backup':'बैकअप','widget.support':'Argus का समर्थन करें',
  'action.home':'घर पर आर्म करें','action.away':'बाहर आर्म करें','action.disarm':'निष्क्रिय करें','action.refresh':'रीफ़्रेश','action.export':'निर्यात','action.restore':'पुनर्स्थापित करें','action.logout':'साइन आउट','action.save':'सहेजें','action.delete':'हटाएँ','action.enable':'सक्षम करें','action.disable':'अक्षम करें','action.open':'Home Assistant में खोलें','action.manage':'Home Assistant में स्वचालन प्रबंधित करें','action.addProfile':'प्रोफ़ाइल जोड़ें','action.addRule':'नियम जोड़ें','action.saveMode':'मोड सहेजें','action.saveName':'नाम सहेजें','action.saveAdvanced':'उन्नत नियंत्रण सहेजें','action.clear':'लॉग साफ़ करें',
  'status.review':'समीक्षाधीन स्थिति','status.unavailable':'अनुपलब्ध','status.active':'सक्रिय','status.disabled':'निष्क्रिय','status.enabled':'सक्षम','status.inactive':'अक्षम','status.configured':'(कॉन्फ़िगर किया गया)','status.empty':'हाल की कोई गतिविधि नहीं','status.event':'इवेंट','status.incident':'घटना','status.open':'खुला',
  'sos.title':'SOS कार्रवाइयाँ','sos.save':'SOS कार्रवाइयाँ सहेजें','sos.saving':'सहेजा जा रहा है…','sos.none':'कोई संगत SOS आउटपुट नहीं है।','sos.saved':'इस इंस्टेंस के लिए SOS कार्रवाइयाँ सहेजी गईं।','sos.permission':'इन आउटपुट को सहेजने के लिए आपकी प्रोफ़ाइल को «SOS प्रबंधित करें» अनुमति की आवश्यकता है।','sos.failed':'SOS कार्रवाइयाँ सहेजी नहीं जा सकीं। SOS प्रबंधित करें अनुमति जांचें।',
  'automation.readOnly':'इस इंस्टेंस से संबंधित Home Assistant स्वचालन (केवल पढ़ने के लिए)।','automation.empty':'इस इंस्टेंस से संबंधित कोई Home Assistant स्वचालन नहीं है।','automation.noCrud':'Argus स्वचालन बनाता या संशोधित नहीं करता है। यह सूची केवल चयनित इंस्टेंस के लिए पढ़ने के लिए है।','automation.dashboard':'Home Assistant स्वचालन डैशबोर्ड खोलें',
  'admin.title':'उन्नत प्रशासन','admin.users':'उपयोगकर्ता, PIN और उपस्थिति','admin.modes':'मोड, सेंसर और सायरन','admin.automations':'Home Assistant स्वचालन','admin.personalization':'मल्टीमीडिया और थीम','admin.forensics':'घटनाएँ और फोरेंसिक','admin.advanced':'उन्नत कॉन्फ़िगरेशन','admin.profiles':'प्रोफ़ाइल और अनुमतियाँ','admin.presence':'उपस्थिति','admin.incidents':'घटनाएँ','admin.audit':'ऑडिट',
  'field.name':'नाम','field.rule':'नियम का नाम','field.home':'घर का नाम','field.noHa':'कोई HA खाता नहीं','field.standard':'मानक','field.admin':'व्यवस्थापक','field.arming':'आर्मिंग विलंब (सेकंड)','field.entry':'प्रवेश विलंब (सेकंड)','field.closed':'आर्म करने से पहले बंद सेंसर की आवश्यकता है','field.mqtt':'MQTT स्थिति प्रकाशित करें','field.people':'नियम को ट्रिगर करने वाले लोग','field.sensors':'सक्रिय सेंसर','field.bypassed':'बाईपास किए गए सेंसर','field.entrySensors':'प्रवेश विलंब वाले सेंसर','field.sirens':'सायरन और आउटपुट','field.panels':'बाहरी पैनल','field.lights':'अलार्म लाइटें','field.lightOptions':'अलार्म लाइट का रंग और फ़्लैश','field.color':'{entity} का रंग','field.noFlash':'कोई फ़्लैश नहीं','field.gentle':'धीमी फ़्लैश','field.rapid':'तेज़ फ़्लैश','field.background':'Argus एक निश्चित डिफ़ॉल्ट पृष्ठभूमि का उपयोग करता है। कस्टम पृष्ठभूमि और एनिमेटेड मौसम सहेजे नहीं जाते हैं।','field.codes':'मौजूदा कोड प्रदर्शित नहीं किए जाते हैं। बदलने के लिए केवल एक नया मान दर्ज करें; बनाए रखने के लिए खाली छोड़ें।','field.armCode':'आर्म करने के लिए कोड आवश्यक है','field.guest':'अतिथि कोड सक्षम करें','field.newGuest':'नया अतिथि कोड','field.duress':'दबाव PIN {configured}',
  'dashboard.loading':'डैशबोर्ड लोड हो रहा है…','dashboard.edit':'✥ डैशबोर्ड संपादित करें','dashboard.done':'✓ संपन्न','dashboard.reset':'लेआउट रीसेट करें','dashboard.resetWidget':'विजेट रीसेट करें','dashboard.hide':'विजेट छुपाएं','dashboard.size':'आकार','dashboard.options':'विकल्प','dashboard.drag':'स्थानांतरित करने के लिए खींचें','dashboard.move':'{widget} को स्थानांतरित करें','dashboard.hidden':'छिपे हुए विजेट','dashboard.show':'{widget} दिखाएं','dashboard.finished':'संपादन समाप्त हुआ','dashboard.restored':'डिफ़ॉल्ट लेआउट पुनर्स्थापित किया गया','dashboard.saved':'स्थिति सहेजी गई','dashboard.blocked':'टकराव के कारण स्थिति अवरुद्ध','dashboard.resized':'आकार {size}','dashboard.widgetRestored':'विजेट रीसेट किया गया','dashboard.visible':'विजेट दृश्यमान','dashboard.invisible':'विजेट छिपा हुआ','dashboard.confirm':'केवल डैशबोर्ड की स्थिति, आकार और दृश्यता रीसेट करें?','dashboard.toolbar':'डैशबोर्ड संपादन',
  'profile.active':'सक्रिय प्रोफ़ाइल: {name}','profile.accessPin':'{name} के लिए एक्सेस PIN','profile.removePin':'{name} के लिए PIN; हटाने के लिए खाली छोड़ें','profile.adminName':'Argus व्यवस्थापक का नाम','profile.disarmPin':'डिसआर्म PIN (यदि लागू हो)',
  'error.unknown':'एक अनपेक्षित त्रुटि हुई।','error.permission':'आपके पास इस कार्रवाई को करने की अनुमति नहीं है।','error.notFound':'Argus इंस्टेंस नहीं मिला।','error.light':'चयनित लाइट Home Assistant में उपलब्ध नहीं है।','error.background':'Argus एक निश्चित डिफ़ॉल्ट पृष्ठभूमि का उपयोग करता है।','error.widgetTitle':'⚠️ विजेट त्रुटि','error.widgetBody':'एक घटक रेंडर नहीं किया जा सका।',
  'activity.armed':'सिस्टम आर्म किया गया','activity.disarmed':'सिस्टम निष्क्रिय किया गया','activity.cancelled':'आर्मिंग रद्द की गई','activity.rejected':'आर्मिंग अस्वीकार की गई','activity.restored':'कॉन्फ़िगरेशन पुनर्स्थापित किया गया','activity.cleared':'ऑडिट लॉग साफ़ किया गया','activity.automation':'स्वचालन निष्पादित किया गया','activity.updated':'कॉन्फ़िगरेशन अद्यतन किया गया','activity.historic':'ऐतिहासिक घटना'
};

const ar:Catalog={
  'app.panel':'لوحة الأمان','app.instance':'المثيل','app.language':'اللغة','app.none':'لا توجد مثيلات Argus مهيأة.','app.setup':'إعداد Argus','app.profile':'اختر ملفاً شخصياً','app.complete':'إكمال الإعداد الأولي',
  'widget.security':'حالة الأمان','widget.activity':'النشاط','widget.automations':'الأتمتة','widget.access':'الوصول وSOS','widget.alarm':'إعدادات الإنذار','widget.backup':'نسخة احتياطية','widget.support':'ادعم Argus',
  'action.home':'تسليح المنزل','action.away':'تسليح خارج المنزل','action.disarm':'إلغاء التسليح','action.refresh':'تحديث','action.export':'تصدير','action.restore':'استعادة','action.logout':'تسجيل الخروج','action.save':'حفظ','action.delete':'حذف','action.enable':'تفعيل','action.disable':'تعطيل','action.open':'فتح في Home Assistant','action.manage':'إدارة الأتمتة في Home Assistant','action.addProfile':'إضافة ملف شخصي','action.addRule':'إضافة قاعدة','action.saveMode':'حفظ الوضع','action.saveName':'حفظ الاسم','action.saveAdvanced':'حفظ عناصر التحكم المتقدمة','action.clear':'مسح السجل',
  'status.review':'الحالة قيد المراجعة','status.unavailable':'غير متوفر','status.active':'نشط','status.disabled':'معطل','status.enabled':'مفعل','status.inactive':'معطل','status.configured':'(مهيأ)','status.empty':'لا يوجد نشاط حديث','status.event':'حدث','status.incident':'حادثة','status.open':'مفتوح',
  'sos.title':'إجراءات SOS','sos.save':'حفظ إجراءات SOS','sos.saving':'جارٍ الحفظ…','sos.none':'لا توجد مخارج SOS متوافقة.','sos.saved':'تم حفظ إجراءات SOS لهذا المثيل.','sos.permission':'يحتاج ملفك الشخصي إلى إذن «إدارة SOS» لحفظ هذه المخارج.','sos.failed':'تعذر حفظ إجراءات SOS. تحقق من إذن إدارة SOS.',
  'automation.readOnly':'أتمتة Home Assistant المرتبطة بهذا المثيل (للقراءة فقط).','automation.empty':'لا توجد أتمتة من Home Assistant مرتبطة بهذا المثيل.','automation.noCrud':'لا ينشئ Argus الأتمتة أو يعدلها. هذه القائمة للقراءة فقط للمثيل المحدد.','automation.dashboard':'فتح لوحة تحكم أتمتة Home Assistant',
  'admin.title':'إدارة متقدمة','admin.users':'المستخدمون وPIN والحضور','admin.modes':'الأوضاع والحساسات والصفارات','admin.automations':'أتمتة Home Assistant','admin.personalization':'الوسائط والسمات','admin.forensics':'الحوادث والتحليل الجنائي','admin.advanced':'إعدادات متقدمة','admin.profiles':'الملفات الشخصية والأذونات','admin.presence':'الحضور','admin.incidents':'الحوادث','admin.audit':'التدقيق',
  'field.name':'الاسم','field.rule':'اسم القاعدة','field.home':'اسم المنزل','field.noHa':'لا يوجد حساب HA','field.standard':'قياسي','field.admin':'مسؤول','field.arming':'تأخير التسليح (بالثواني)','field.entry':'تأخير الدخول (بالثواني)','field.closed':'طلب إغلاق الحساسات قبل التسليح','field.mqtt':'نشر حالة MQTT','field.people':'الأشخاص الذين يشغلون القاعدة','field.sensors':'الحساسات النشطة','field.bypassed':'الحساسات المتجاوزة','field.entrySensors':'حساسات بتأخير دخول','field.sirens':'الصفارات والمخارج','field.panels':'اللوحات الخارجية','field.lights':'أضواء الإنذار','field.lightOptions':'لون وميض أضواء الإنذار','field.color':'لون {entity}','field.noFlash':'بدون وميض','field.gentle':'وميض هادئ','field.rapid':'وميض سريع','field.background':'يستخدم Argus خلفية افتراضية ثابتة واحدة. لا يتم تشغيل أو حفظ الخلفيات المخصصة والطقس المتحرك.','field.codes':'الرموز الحالية لا يتم عرضها. اكتب قيمة فقط لاستبدالها؛ اترك الحقل فارغاً للاحتفاظ بها.','field.armCode':'طلب رمز للتسليح','field.guest':'تمكين رمز الضيف','field.newGuest':'رمز ضيف جديد','field.duress':'رمز الإكراه PIN {configured}',
  'dashboard.loading':'جارٍ تحميل لوحة التحكم…','dashboard.edit':'✥ تعديل اللوحة','dashboard.done':'✓ تم','dashboard.reset':'إعادة تعيين المخطط','dashboard.resetWidget':'إعادة تعيين الأداة','dashboard.hide':'إخفاء الأداة','dashboard.size':'الحجم','dashboard.options':'خيارات','dashboard.drag':'اسحب للتحريك','dashboard.move':'تحريك {widget}','dashboard.hidden':'الأدوات المخفية','dashboard.show':'إظهار {widget}','dashboard.finished':'تم الانتهاء من التعديل','dashboard.restored':'تمت استعادة المخطط الافتراضي','dashboard.saved':'تم حفظ الموضع','dashboard.blocked':'الموضع محجوب بسبب التصادم','dashboard.resized':'الحجم {size}','dashboard.widgetRestored':'تمت إعادة تعيين الأداة','dashboard.visible':'الأداة مرئية','dashboard.invisible':'الأداة مخفية','dashboard.confirm':'هل تريد إعادة تعيين مواضع وأحجام ورؤية اللوحة فقط؟','dashboard.toolbar':'شريط تحرير اللوحة',
  'profile.active':'الملف الشخصي النشط: {name}','profile.accessPin':'رمز PIN للوصول لـ {name}','profile.removePin':'رمز PIN لـ {name}؛ اتركه فارغاً للحذف','profile.adminName':'اسم مسؤول Argus','profile.disarmPin':'رمز PIN لإلغاء التسليح (إن وجد)',
  'error.unknown':'حدث خطأ غير متوقع.','error.permission':'ليس لديك إذن لتنفيذ هذا الإجراء.','error.notFound':'لم يتم العثور على مثيل Argus.','error.light':'الضوء المحدد غير متوفر في Home Assistant.','error.background':'يستخدم Argus خلفية افتراضية ثابتة.','error.widgetTitle':'⚠️ خطأ في الأداة','error.widgetBody':'تعذر عرض أحد المكونات.',
  'activity.armed':'تم تسليح النظام','activity.disarmed':'تم إلغاء تسليح النظام','activity.cancelled':'تم إلغاء التسليح','activity.rejected':'تم رفض التسليح','activity.restored':'تمت استعادة التكوين','activity.cleared':'تم مسح سجل التدقيق','activity.automation':'تم تنفيذ الأتمتة','activity.updated':'تم تحديث التكوين','activity.historic':'حدث تاريخي'
};

const ko:Catalog={
  'app.panel':'보안 패널','app.instance':'인스턴스','app.language':'언어','app.none':'구성된 Argus 인스턴스가 없습니다.','app.setup':'Argus 설정','app.profile':'프로필 선택','app.complete':'초기 설정 완료',
  'widget.security':'보안 상태','widget.activity':'활동','widget.automations':'자동화','widget.access':'접근 및 SOS','widget.alarm':'경보 구성','widget.backup':'백업','widget.support':'Argus 후원',
  'action.home':'재택 경계','action.away':'외출 경계','action.disarm':'경계 해제','action.refresh':'새로 고침','action.export':'내보내기','action.restore':'복원','action.logout':'로그아웃','action.save':'저장','action.delete':'삭제','action.enable':'활성화','action.disable':'비활성화','action.open':'Home Assistant에서 열기','action.manage':'Home Assistant에서 자동화 관리','action.addProfile':'프로필 추가','action.addRule':'규칙 추가','action.saveMode':'모드 저장','action.saveName':'이름 저장','action.saveAdvanced':'고급 제어 저장','action.clear':'로그 삭제',
  'status.review':'상태 검토 중','status.unavailable':'사용 불가','status.active':'활성','status.disabled':'비활성','status.enabled':'활성화됨','status.inactive':'비활성화됨','status.configured':'(구성됨)','status.empty':'최근 활동 없음','status.event':'이벤트','status.incident':'사고','status.open':'열림',
  'sos.title':'SOS 동작','sos.save':'SOS 동작 저장','sos.saving':'저장 중…','sos.none':'호환되는 SOS 출력이 없습니다.','sos.saved':'이 인스턴스에 대한 SOS 동작이 저장되었습니다.','sos.permission':'이 출력을 저장하려면 프로필에 «SOS 관리» 권한이 필요합니다.','sos.failed':'SOS 동작을 저장하지 못했습니다. SOS 관리 권한을 확인하세요.',
  'automation.readOnly':'이 인스턴스와 관련된 Home Assistant 자동화 (읽기 전용).','automation.empty':'이 인스턴스와 관련된 Home Assistant 자동화가 없습니다.','automation.noCrud':'Argus는 자동화를 생성하거나 수정하지 않습니다. 이 목록은 선택한 인스턴스에 대해 읽기 전용입니다.','automation.dashboard':'Home Assistant 자동화 대시보드 열기',
  'admin.title':'고급 관리','admin.users':'사용자, PIN 및 재실','admin.modes':'모드, 센서 및 사이렌','admin.automations':'Home Assistant 자동화','admin.personalization':'멀티미디어 및 테마','admin.forensics':'사고 및 포렌식','admin.advanced':'고급 구성','admin.profiles':'프로필 및 권한','admin.presence':'재실','admin.incidents':'사고 내역','admin.audit':'감사 로그',
  'field.name':'이름','field.rule':'규칙 이름','field.home':'홈 이름','field.noHa':'HA 계정 없음','field.standard':'일반','field.admin':'관리자','field.arming':'경계 설정 지연 (초)','field.entry':'진입 지연 (초)','field.closed':'경계 설정 전 센서 닫힘 필수','field.mqtt':'MQTT 상태 게시','field.people':'규칙을 트리거하는 사용자','field.sensors':'활성 센서','field.bypassed':'우회된 센서','field.entrySensors':'진입 지연 센서','field.sirens':'사이렌 및 출력','field.panels':'외부 패널','field.lights':'경보 조명','field.lightOptions':'경보 조명 색상 및 점멸','field.color':'{entity} 색상','field.noFlash':'점멸 없음','field.gentle':'부드러운 점멸','field.rapid':'빠른 점멸','field.background':'Argus는 단일 고정 기본 배경을 사용합니다. 사용자 지정 배경 및 애니메이션 날씨는 실행되거나 저장되지 않습니다.','field.codes':'기존 코드는 표시되지 않습니다. 교체할 때만 값을 입력하고, 유지하려면 비워 두세요.','field.armCode':'경계 설정 시 코드 필요','field.guest':'게스트 코드 활성화','field.newGuest':'새 게스트 코드','field.duress':'협박 PIN {configured}',
  'dashboard.loading':'대시보드 불러오는 중…','dashboard.edit':'✥ 대시보드 편집','dashboard.done':'✓ 완료','dashboard.reset':'레이아웃 재설정','dashboard.resetWidget':'위젯 재설정','dashboard.hide':'위젯 숨기기','dashboard.size':'크기','dashboard.options':'옵션','dashboard.drag':'드래그하여 이동','dashboard.move':'{widget} 이동','dashboard.hidden':'숨겨진 위젯','dashboard.show':'{widget} 표시','dashboard.finished':'편집 완료','dashboard.restored':'기본 레이아웃 복원됨','dashboard.saved':'위치 저장됨','dashboard.blocked':'충돌로 인해 위치 차단됨','dashboard.resized':'크기 {size}','dashboard.widgetRestored':'위젯 초기화됨','dashboard.visible':'위젯 표시됨','dashboard.invisible':'위젯 숨겨짐','dashboard.confirm':'대시보드의 위치, 크기 및 표시 여부만 재설정하시겠습니까?','dashboard.toolbar':'대시보드 편집',
  'profile.active':'활성 프로필: {name}','profile.accessPin':'{name} 액세스 PIN','profile.removePin':'{name} PIN (삭제하려면 비워 둠)','profile.adminName':'Argus 관리자 이름','profile.disarmPin':'경계 해제 PIN (해당되는 경우)',
  'error.unknown':'예기치 않은 오류가 발생했습니다.','error.permission':'이 작업을 수행할 권한이 없습니다.','error.notFound':'Argus 인스턴스를 찾을 수 없습니다.','error.light':'선택한 조명을 Home Assistant에서 사용할 수 없습니다.','error.background':'Argus는 고정 기본 배경을 사용합니다.','error.widgetTitle':'⚠️ 위젯 오류','error.widgetBody':'구성 요소를 렌더링할 수 없습니다.',
  'activity.armed':'시스템 경계 설정됨','activity.disarmed':'시스템 경계 해제됨','activity.cancelled':'경계 설정 취소됨','activity.rejected':'경계 설정 거부됨','activity.restored':'구성 복원됨','activity.cleared':'감사 로그 삭제됨','activity.automation':'자동화 실행됨','activity.updated':'구성 업데이트됨','activity.historic':'과거 기록 이벤트'
};

const ja:Catalog={
  'app.panel':'セキュリティパネル','app.instance':'インスタンス','app.language':'言語','app.none':'Argus インスタンスが設定されていません。','app.setup':'Argus を設定','app.profile':'プロファイルを選択','app.complete':'初期設定を完了',
  'widget.security':'セキュリティ状態','widget.activity':'アクティビティ','widget.automations':'自動化','widget.access':'アクセスとSOS','widget.alarm':'アラーム設定','widget.backup':'バックアップ','widget.support':'Argus を支援',
  'action.home':'在宅警戒','action.away':'外出警戒','action.disarm':'警戒解除','action.refresh':'更新','action.export':'エクスポート','action.restore':'復元','action.logout':'ログアウト','action.save':'保存','action.delete':'削除','action.enable':'有効化','action.disable':'無効化','action.open':'Home Assistant で開く','action.manage':'Home Assistant で自動化を管理','action.addProfile':'プロファイルを追加','action.addRule':'ルールを追加','action.saveMode':'モードを保存','action.saveName':'名前を保存','action.saveAdvanced':'詳細制御を保存','action.clear':'ログを消去',
  'status.review':'確認中','status.unavailable':'利用不可','status.active':'有効','status.disabled':'無効','status.enabled':'有効','status.inactive':'無効','status.configured':'(設定済み)','status.empty':'最近のアクティビティはありません','status.event':'イベント','status.incident':'インシデント','status.open':'オープン',
  'sos.title':'SOS アクション','sos.save':'SOS アクションを保存','sos.saving':'保存中…','sos.none':'互換性のある SOS 出力がありません。','sos.saved':'このインスタンスの SOS アクションが保存されました。','sos.permission':'これらの出力を保存するにはプロファイルに「SOS 管理」権限が必要です。','sos.failed':'SOS アクションを保存できませんでした。SOS 管理権限を確認してください。',
  'automation.readOnly':'このインスタンスに関連する Home Assistant 自動化 (読み取り専用)。','automation.empty':'このインスタンスに関連する Home Assistant 自動化はありません。','automation.noCrud':'Argus は自動化の作成や変更を行いません。この一覧は選択されたインスタンスに対して読み取り専用です。','automation.dashboard':'Home Assistant 自動化ダッシュボードを開く',
  'admin.title':'詳細管理','admin.users':'ユーザー、PIN、在宅','admin.modes':'モード、センサー、サイレン','admin.automations':'Home Assistant 自動化','admin.personalization':'マルチメディアとテーマ','admin.forensics':'インシデントとフォレンジック','admin.advanced':'詳細設定','admin.profiles':'プロファイルと権限','admin.presence':'在宅ルール','admin.incidents':'インシデント','admin.audit':'監査ログ',
  'field.name':'名前','field.rule':'ルール名','field.home':'ホーム名','field.noHa':'HA アカウントなし','field.standard':'標準','field.admin':'管理者','field.arming':'警戒開始遅延 (秒)','field.entry':'侵入遅延 (秒)','field.closed':'警戒開始前にセンサーの閉鎖を必須とする','field.mqtt':'MQTT ステータスを発行','field.people':'ルールをトリガーするユーザー','field.sensors':'アクティブセンサー','field.bypassed':'バイパスされたセンサー','field.entrySensors':'侵入遅延のあるセンサー','field.sirens':'サイレンと出力','field.panels':'外部パネル','field.lights':'アラームライト','field.lightOptions':'アラームライトの色と点滅','field.color':'{entity} の色','field.noFlash':'点滅なし','field.gentle':'穏やかな点滅','field.rapid':'高速点滅','field.background':'Argus は単一の固定デフォルト背景を使用します。カスタム背景やアニメーション天気は実行および保存されません。','field.codes':'既存のコードは表示されません。置換する場合のみ値を入力してください。保持する場合は空のままにしてください。','field.armCode':'警戒開始にコードを要求','field.guest':'ゲストコードを有効化','field.newGuest':'新しいゲストコード','field.duress':'脅迫 PIN {configured}',
  'dashboard.loading':'ダッシュボードを読み込み中…','dashboard.edit':'✥ ダッシュボードを編集','dashboard.done':'✓ 完了','dashboard.reset':'レイアウトをリセット','dashboard.resetWidget':'ウィジェットをリセット','dashboard.hide':'ウィジェットを非表示','dashboard.size':'サイズ','dashboard.options':'オプション','dashboard.drag':'ドラッグして移動','dashboard.move':'{widget} を移動','dashboard.hidden':'非表示のウィジェット','dashboard.show':'{widget} を表示','dashboard.finished':'編集が完了しました','dashboard.restored':'デフォルトのレイアウトに戻しました','dashboard.saved':'位置が保存されました','dashboard.blocked':'衝突のため位置がブロックされました','dashboard.resized':'サイズ {size}','dashboard.widgetRestored':'ウィジェットがリセットされました','dashboard.visible':'ウィジェットを表示','dashboard.invisible':'ウィジェットを非表示','dashboard.confirm':'ダッシュボードの位置、サイズ、表示状態のみをリセットしますか？','dashboard.toolbar':'ダッシュボード編集',
  'profile.active':'アクティブなプロファイル: {name}','profile.accessPin':'{name} のアクセス PIN','profile.removePin':'{name} の PIN (削除する場合は空に設定)','profile.adminName':'Argus 管理者名','profile.disarmPin':'警戒解除 PIN (該当する場合)',
  'error.unknown':'予期しないエラーが発生しました。','error.permission':'この操作を実行する権限がありません。','error.notFound':'Argus インスタンスが見つかりません。','error.light':'選択したライトは Home Assistant で使用できません。','error.background':'Argus は固定のデフォルト背景を使用します。','error.widgetTitle':'⚠️ ウィジェットエラー','error.widgetBody':'コンポーネントをレンダリングできませんでした。',
  'activity.armed':'システム警戒開始','activity.disarmed':'システム警戒解除','activity.cancelled':'警戒開始がキャンセルされました','activity.rejected':'警戒開始が拒否されました','activity.restored':'設定が復元されました','activity.cleared':'監査ログが消去されました','activity.automation':'自動化が実行されました','activity.updated':'設定が更新されました','activity.historic':'履歴イベント'
};

const uk:Catalog={
  'app.panel':'Панель безпеки','app.instance':'Екземпляр','app.language':'Мова','app.none':'Екземпляри Argus не налаштовано.','app.setup':'Налаштувати Argus','app.profile':'Виберіть профіль','app.complete':'Завершити початкове налаштування',
  'widget.security':'Стан безпеки','widget.activity':'Активність','widget.automations':'Автоматизації','widget.access':'Доступ і SOS','widget.alarm':'Налаштування сигналізації','widget.backup':'Резервна копія','widget.support':'Підтримати Argus',
  'action.home':'Увімкнути охорону вдома','action.away':'Увімкнути охорону поза домом','action.disarm':'Зняти з охорони','action.refresh':'Оновити','action.export':'Експортувати','action.restore':'Відновити','action.logout':'Вийти','action.save':'Зберегти','action.delete':'Видалити','action.enable':'Увімкнути','action.disable':'Вимкнути','action.open':'Відкрити в Home Assistant','action.manage':'Керувати автоматизаціями в Home Assistant','action.addProfile':'Додати профіль','action.addRule':'Додати правило','action.saveMode':'Зберегти режим','action.saveName':'Зберегти назву','action.saveAdvanced':'Зберегти розширені параметри','action.clear':'Очистити журнал',
  'status.review':'Стан на перевірці','status.unavailable':'недоступно','status.active':'активний','status.disabled':'вимкнено','status.enabled':'Увімкнено','status.inactive':'Вимкнено','status.configured':'(налаштовано)','status.empty':'Немає недавньої активності','status.event':'Подія','status.incident':'Інцидент','status.open':'відкрито',
  'sos.title':'Дії SOS','sos.save':'Зберегти дії SOS','sos.saving':'Збереження…','sos.none':'Немає сумісних виходів SOS.','sos.saved':'Дії SOS збережено для цього екземпляра.','sos.permission':'Ваш профіль потребує дозволу «Керування SOS» для збереження цих виходів.','sos.failed':'Не вдалося зберегти дії SOS. Перевірте дозвіл Керування SOS.',
  'automation.readOnly':'Автоматизації Home Assistant, пов’язані з цим екземпляром (тільки читання).','automation.empty':'Немає автоматизацій Home Assistant, пов’язаних з цим екземпляром.',
  'automation.noCrud':'Argus не створює та не змінює автоматизації. Цей список доступний лише для читання обраного екземпляра.',
  'automation.dashboard':'Відкрити панель автоматизацій Home Assistant',
  'admin.title':'Розширене адміністрування','admin.users':'Користувачі, PIN і присутність','admin.modes':'Режими, датчики та сирени','admin.automations':'Автоматизації Home Assistant','admin.personalization':'Мультимедіа та теми','admin.forensics':'Інциденти та криміналістика','admin.advanced':'Розширена конфігурація','admin.profiles':'Профілі та дозволи','admin.presence':'Присутність','admin.incidents':'Інциденти','admin.audit':'Аудит',
  'field.name':'Назва','field.rule':'Назва правила','field.home':'Назва дому','field.noHa':'Без облікового запису HA','field.standard':'Стандартний','field.admin':'Адміністратор','field.arming':'Затримка постановки (секунди)','field.entry':'Затримка входу (секунди)','field.closed':'Вимагати закриття датчиків перед постановкою','field.mqtt':'Публікувати стан MQTT','field.people':'Особи, які активують правило','field.sensors':'Активні датчики','field.bypassed':'Обійдені датчики (байпас)','field.entrySensors':'Датчики із затримкою входу','field.sirens':'Сирени та виходи','field.panels':'Зовнішні панелі','field.lights':'Сигнальні лампи','field.lightOptions':'Колір і миготіння ламп','field.color':'Колір {entity}','field.noFlash':'Без миготіння','field.gentle':'М’яке миготіння','field.rapid':'Швидке миготіння','field.background':'Argus використовує єдиний фіксований фон за замовчуванням. Власні фони та анімована погода не підтримуються.','field.codes':'Існуючі коди не відображаються. Введіть значення лише для заміни; залиште порожнім для збереження.','field.armCode':'Вимагати код для постановки','field.guest':'Увімкнути гостьовий код','field.newGuest':'Новий гостьовий код','field.duress':'PIN під примусом {configured}',
  'dashboard.loading':'Завантаження панелі…','dashboard.edit':'✥ Редагувати панель','dashboard.done':'✓ Готово','dashboard.reset':'Скинути макет','dashboard.resetWidget':'Скинути віджет','dashboard.hide':'Сховати віджет','dashboard.size':'Розмір','dashboard.options':'Параметри','dashboard.drag':'Перетягніть для переміщення','dashboard.move':'Перемістити {widget}','dashboard.hidden':'Приховані віджети','dashboard.show':'Показати {widget}','dashboard.finished':'Редагування завершено','dashboard.restored':'Відновлено макет за замовчуванням','dashboard.saved':'Позицію збережено','dashboard.blocked':'Позицію заблоковано через зіткнення','dashboard.resized':'Розмір {size}','dashboard.widgetRestored':'Віджет скинуто','dashboard.visible':'Віджет відображається','dashboard.invisible':'Віджет приховано','dashboard.confirm':'Скинути лише позиції, розміри та видимість панелі?','dashboard.toolbar':'Редагування панелі',
  'profile.active':'Активний профіль: {name}','profile.accessPin':'PIN доступу для {name}','profile.removePin':'PIN для {name}; залиште порожнім для видалення','profile.adminName':'Ім’я адміністратора Argus','profile.disarmPin':'PIN для зняття з охорони (якщо застосовно)',
  'error.unknown':'Сталася неочікувана помилка.','error.permission':'У вас немає дозволу на виконання цієї дії.','error.notFound':'Екземпляр Argus не знайдено.','error.light':'Обране світло недоступне в Home Assistant.','error.background':'Argus використовує фіксований стандартний фон.','error.widgetTitle':'⚠️ Помилка віджета','error.widgetBody':'Не вдалося відрендерити компонент.',
  'activity.armed':'Систему поставлено на охорону','activity.disarmed':'Систему знято з охорони','activity.cancelled':'Постановку на охорону скасовано','activity.rejected':'Постановку на охорону відхилено','activity.restored':'Конфігурацію відновлено','activity.cleared':'Журнал аудиту очищено','activity.automation':'Автоматизацію виконано','activity.updated':'Конфігурацію оновлено','activity.historic':'Історична подія'
};

const catalog:Record<ArgusLocale,Catalog>={es,en,fr,pt,it,'zh-Hans':zhHans,'zh-Hant':zhHant,hi,ar,ko,ja,uk};
const errorKeys:Record<string,I18nKey>={unauthorized:'error.permission',not_found:'error.notFound',invalid_light:'error.light',light_unavailable:'error.light',unsupported:'error.background','Requires Home Assistant administrator privileges':'error.permission','Requires Argus administrator privileges':'error.permission','Valid Argus session required':'error.permission','Argus profile is disabled or deleted':'error.permission','Argus entry not found':'error.notFound','Argus uses a fixed default background':'error.background'};
const fill=(text:string,values?:Values)=>Object.entries(values||{}).reduce((result,[key,value])=>result.replaceAll(`{${key}}`,String(value)),text);
export const translate=(locale:ArgusLocale,key:I18nKey,values?:Values)=>fill(catalog[locale][key]??es[key],values);
export const localizeError=(locale:ArgusLocale,cause:unknown)=>{const error=cause as {code?:string;message?:string};return translate(locale,errorKeys[error?.code||'']||errorKeys[error?.message||'']||'error.unknown')};
const Context=createContext<I18n|null>(null);
export function I18nProvider({hass,children}:{hass:HomeAssistant;children:React.ReactNode}){const configured=hass.config?.language==='zh'?'zh-Hans':hass.config?.language;const initial=ARGUS_LOCALES.includes(configured as ArgusLocale)?configured as ArgusLocale:'es';const[locale,setLocale]=useState<ArgusLocale>(initial);const value=useMemo<I18n>(()=>({locale,setLocale,t:(key,values)=>translate(locale,key,values),error:cause=>localizeError(locale,cause)}),[locale]);return <Context.Provider value={value}><div dir={locale==='ar'?'rtl':'ltr'} lang={locale} data-argus-locale={locale}>{children}</div></Context.Provider>}
export function useI18n(){const value=useContext(Context);if(!value)throw new Error('Argus I18nProvider is required');return value}
