name: Retired v2.0.55 synchronization

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  retired:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Retired'
